=== Pratikshit26/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-schema-model/maindoc/UBL-TradeItemLocationProfile-2.3.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "json-schema-model/maindoc/UBL-TradeItemLocationProfile-2.3.json",
  "description": "\n  Library:           OASIS Universal Business Language (UBL) 2.3 OS\n                     http://docs.oasis-open.org/ubl/os-UBL-2.3/\n  Release Date:      15 June 2021\n  Module:            json-schema-model/maindoc/UBL-TradeItemLocationProfile-2.3.json\n  Generated on:      2021-12-15 21:56z\n  Copyright (c) OASIS Open 2021. All Rights Reserved.\n\n\n  OASIS takes no position regarding the validity or scope of any \n  intellectual property or other rights that might be claimed to pertain \n  to the implementation or use of the technology described in this \n  document or the extent to which any license under such rights \n  might or might not be available; neither does it represent that it has \n  made any effort to identify any such rights. Information on OASIS's \n  procedures with respect to rights in OASIS specifications can be \n  found at the OASIS website. Copies of claims of rights made \n  available for publication and any assurances of licenses to be made \n  available, or the result of an attempt made to obtain a general \n  license or permission for the use of such proprietary rights by \n  implementors or users of this specification, can be obtained from \n  the OASIS Executive Director.\n\n  OASIS invites any interested party to bring to its attention any \n  copyrights, patents or patent applications, or other proprietary \n  rights which may cover technology that may be required to \n  implement this specification. Please address the information to the \n  OASIS Executive Director.\n  \n  This document and translations of it may be copied and furnished to \n  others, and derivative works that comment on or otherwise explain \n  it or assist in its implementation may be prepared, copied, \n  published and distributed, in whole or in part, without restriction of \n  any kind, provided that the above copyright notice and this \n  paragraph are included on all such copies and derivative works. \n  However, this document itself may not be modified in any way, \n  such as by removing the copyright notice or references to OASIS, \n  except as needed for the purpose of developing OASIS \n  specifications, in which case the procedures for copyrights defined \n  in the OASIS Intellectual Property Rights document must be \n  followed, or as required to translate it into languages other than \n  English. \n\n  The limited permissions granted above are perpetual and will not be \n  revoked by OASIS or its successors or assigns. \n\n  This document and the information contained herein is provided on \n  an \"AS IS\" basis and OASIS DISCLAIMS ALL WARRANTIES, \n  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY \n  WARRANTY THAT THE USE OF THE INFORMATION HEREIN \n  WILL NOT INFRINGE ANY RIGHTS OR ANY IMPLIED \n  WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A \n  PARTICULAR PURPOSE.    \n",
  "required": ["TradeItemLocationProfile"],
  "properties": {
    "_D": {
      "description": "Document ABIE XML namespace string",
      "type": "string"
    },
    "_A": {
      "description": "Library ABIE XML namespace string (for ASBIEs)",
      "type": "string"
    },
    "_B": {
      "description": "BBIE XML namespace string",
      "type": "string"
    },
    "_E": {
      "description": "Extension scaffolding XML namespace string",
      "type": "string"
    },
    "TradeItemLocationProfile": {
      "description": "A document specifying trade item attributes relating to replenishment policies.",
      "$ref": "#/definitions/TradeItemLocationProfile"
    }
  },
  "additionalProperties": false,
  "type": "object",
  "definitions": {
    "TradeItemLocationProfile": {
      "title": "Trade Item Location Profile. Details",
      "description": "A document specifying trade item attributes relating to replenishment policies.",
      "required": [
        "ID",
        "IssueDate",
        "Period",
        "SenderParty",
        "ReceiverParty",
        "ItemManagementProfile"
      ],
      "properties": {
        "UBLExtensions": {
          "title": "UBLExtensions",
          "description": "An optional set of extensions to the committee model",
          "items": {
            "$ref": "../common/UBL-CommonExtensionComponents-2.3.json#/definitions/UBLExtensions"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },

        "UBLVersionID": {
          "title": "Trade Item Location Profile. UBL Version Identifier. Identifier",
          "description": "Identifies the earliest version of the UBL 2 schema for this document type that defines all of the elements that might be encountered in the current instance.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UBLVersionID"
        },
        "CustomizationID": {
          "title": "Trade Item Location Profile. Customization Identifier. Identifier",
          "description": "Identifies a user-defined customization of UBL for a specific use.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CustomizationID"
        },
        "ProfileID": {
          "title": "Trade Item Location Profile. Profile Identifier. Identifier",
          "description": "Identifies a user-defined profile of the customization of UBL being used.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileID"
        },
        "ProfileExecutionID": {
          "title": "Trade Item Location Profile. Profile Execution Identifier. Identifier",
          "description": "Identifies an instance of executing a profile, to associate all transactions in a collaboration.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileExecutionID"
        },
        "ID": {
          "title": "Trade Item Location Profile. Identifier",
          "description": "An identifier for this document, assigned by the sender.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ID"
        },
        "CopyIndicator": {
          "title": "Trade Item Location Profile. Copy_ Indicator. Indicator",
          "description": "Indicates whether this document is a copy (true) or not (false).",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CopyIndicator"
        },
        "UUID": {
          "title": "Trade Item Location Profile. UUID. Identifier",
          "description": "A universally unique identifier for an instance of this document.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UUID"
        },
        "IssueDate": {
          "title": "Trade Item Location Profile. Issue Date. Date",
          "description": "The date, assigned by the sender, on which this document was issued.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueDate"
        },
        "IssueTime": {
          "title": "Trade Item Location Profile. Issue Time. Time",
          "description": "The time, assigned by the sender, at which this document was issued.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueTime"
        },
        "Note": {
          "title": "Trade Item Location Profile. Note. Text",
          "description": "Free-form text pertinent to this document, conveying information that is not contained explicitly in other structures.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/Note"
          },
          "minItems": 1,
          "type": "array"
        },
        "ProfileStatusCode": {
          "title": "Trade Item Location Profile. Profile_ Status Code. Code",
          "description": "A code signifying the status of this Trade Item Location Profile.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileStatusCode"
        },
        "Period": {
          "title": "Trade Item Location Profile. Period",
          "description": "An association to Period.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Period"
        },
        "DocumentReference": {
          "title": "Trade Item Location Profile. Document Reference",
          "description": "A reference to another document associated with this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/DocumentReference"
          },
          "minItems": 1,
          "type": "array"
        },
        "Signature": {
          "title": "Trade Item Location Profile. Signature",
          "description": "A signature applied to this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Signature"
          },
          "minItems": 1,
          "type": "array"
        },
        "SenderParty": {
          "title": "Trade Item Location Profile. Sender_ Party. Party",
          "description": "The sender.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/SenderParty"
        },
        "ReceiverParty": {
          "title": "Trade Item Location Profile. Receiver_ Party. Party",
          "description": "The receiver.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ReceiverParty"
        },
        "BuyerCustomerParty": {
          "title": "Trade Item Location Profile. Buyer_ Customer Party. Customer Party",
          "description": "The buyer.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/BuyerCustomerParty"
        },
        "SellerSupplierParty": {
          "title": "Trade Item Location Profile. Seller_ Supplier Party. Supplier Party",
          "description": "The seller.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/SellerSupplierParty"
        },
        "ItemManagementProfile": {
          "title": "Trade Item Location Profile. Item Management Profile",
          "description": "A profile specifying replenishment policies for a particular trade item.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ItemManagementProfile"
          },
          "minItems": 1,
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object"
    }
  }
}

=== Pratikshit26/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-model/UBL-TradeItemLocationProfile-2.1-Example.json
{
  "_D": "urn:oasis:names:specification:ubl:schema:xsd:TradeItemLocationProfile-2",
  "_A": "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
  "_B": "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2",
  "TradeItemLocationProfile": {
    "UBLVersionID": { "_": "2.1" },
    "ProfileID": {
      "_": "bpid:urn:oasis:names:draft:bpss:ubl-2-1-cpfr-trade-item-location-profile"
    },
    "ID": { "_": "TILP758494" },
    "CopyIndicator": { "_": false },
    "UUID": { "_": "349ABBAE-DF9D-40B4-849F-94C5FF9D1AF4" },
    "IssueDate": { "_": "2005-01-10" },
    "IssueTime": { "_": "12:00:01.000Z" },
    "Note": [{ "_": "sample" }],
    "ProfileStatusCode": { "_": "NEW" },
    "Period": {
      "StartDate": { "_": "2005-02-26" },
      "EndDate": { "_": "2005-12-26" }
    },
    "SenderParty": {
      "PartyIdentification": [
        {
          "ID": { "_": "6903148000007" }
        }
      ],
      "PartyName": [
        {
          "Name": { "_": "Consortial" }
        }
      ],
      "PostalAddress": {
        "StreetName": { "_": "Busy Street" },
        "BuildingName": { "_": "Thereabouts" },
        "BuildingNumber": { "_": "56A" },
        "CityName": { "_": "Farthing" },
        "PostalZone": { "_": "AA99 1BB" },
        "CountrySubentity": { "_": "Heremouthshire" },
        "AddressLine": [
          {
            "Line": { "_": "The Roundabout" }
          }
        ],
        "Country": {
          "IdentificationCode": { "_": "GB" }
        }
      },
      "PartyTaxScheme": [
        {
          "RegistrationName": { "_": "Farthing Purchasing Consortium" },
          "CompanyID": { "_": "175 269 2355" },
          "ExemptionReason": [{ "_": "N/A" }],
          "TaxScheme": {
            "ID": { "_": "VAT" },
            "TaxTypeCode": { "_": "VAT" }
          }
        }
      ],
      "Contact": {
        "Name": { "_": "Mrs Bouquet" },
        "Telephone": { "_": "0158 1233714" },
        "Telefax": { "_": "0158 1233856" },
        "ElectronicMail": { "_": "bouquet@fpconsortial.co.uk" }
      }
    },
    "ReceiverParty": {
      "PartyIdentification": [
        {
          "ID": { "_": "2203148000007" }
        }
      ],
      "PartyName": [
        {
          "Name": { "_": "IYT Corporation" }
        }
      ],
      "PostalAddress": {
        "StreetName": { "_": "Avon Way" },
        "BuildingName": { "_": "Thereabouts" },
        "BuildingNumber": { "_": "56A" },
        "CityName": { "_": "Bridgtow" },
        "PostalZone": { "_": "ZZ99 1ZZ" },
        "CountrySubentity": { "_": "Avon" },
        "AddressLine": [
          {
            "Line": { "_": "3rd Floor, Room 5" }
          }
        ],
        "Country": {
          "IdentificationCode": { "_": "GB" }
        }
      },
      "PartyTaxScheme": [
        {
          "RegistrationName": { "_": "Bridgtow District Council" },
          "CompanyID": { "_": "12356478" },
          "ExemptionReason": [{ "_": "Local Authority" }],
          "TaxScheme": {
            "ID": { "_": "UK VAT" },
            "TaxTypeCode": { "_": "VAT" }
          }
        }
      ],
      "Contact": {
        "Name": { "_": "Mr Fred Churchill" },
        "Telephone": { "_": "0127 2653214" },
        "Telefax": { "_": "0127 2653215" },
        "ElectronicMail": { "_": "fred@iytcorporation.gov.uk" }
      }
    },
    "BuyerCustomerParty": {
      "Party": {
        "PartyIdentification": [
          {
            "ID": { "_": "0012345000359" }
          }
        ]
      }
    },
    "SellerSupplierParty": {
      "Party": {
        "PartyIdentification": [
          {
            "ID": { "_": "0012345000058" }
          }
        ]
      }
    },
    "ItemManagementProfile": [
      {
        "FrozenPeriodDaysNumeric": { "_": 3 },
        "MinimumInventoryQuantity": { "_": 8 },
        "MultipleOrderQuantity": { "_": 1 },
        "OrderIntervalDaysNumeric": { "_": 3 },
        "ReplenishmentOwnerDescription": [{ "_": "Ownere-321" }],
        "TargetServicePercent": { "_": 1 },
        "TargetInventoryQuantity": { "_": 20, "unitCode": "KGM" },
        "EffectivePeriod": {
          "StartDate": { "_": "2005-02-26" },
          "EndDate": { "_": "2005-12-26" }
        },
        "Item": {
          "Description": [{ "_": "Acme beeswax" }],
          "Name": { "_": "beeswax" },
          "BuyersItemIdentification": {
            "ID": { "_": "6578489" }
          },
          "SellersItemIdentification": {
            "ID": { "_": "17589683" }
          },
          "StandardItemIdentification": {
            "ID": { "_": "00123450000584" }
          }
        },
        "ItemLocationQuantity": {
          "LeadTimeMeasure": { "_": 3, "unitCode": "DAY" },
          "MinimumQuantity": { "_": 2 }
        }
      }
    ]
  }
}
