=== Pratikshit26/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-schema-model/maindoc/UBL-TransportProgressStatusRequest-2.3.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "json-schema-model/maindoc/UBL-TransportProgressStatusRequest-2.3.json",
  "description": "\n  Library:           OASIS Universal Business Language (UBL) 2.3 OS\n                     http://docs.oasis-open.org/ubl/os-UBL-2.3/\n  Release Date:      15 June 2021\n  Module:            json-schema-model/maindoc/UBL-TransportProgressStatusRequest-2.3.json\n  Generated on:      2021-12-15 21:56z\n  Copyright (c) OASIS Open 2021. All Rights Reserved.\n\n\n  OASIS takes no position regarding the validity or scope of any \n  intellectual property or other rights that might be claimed to pertain \n  to the implementation or use of the technology described in this \n  document or the extent to which any license under such rights \n  might or might not be available; neither does it represent that it has \n  made any effort to identify any such rights. Information on OASIS's \n  procedures with respect to rights in OASIS specifications can be \n  found at the OASIS website. Copies of claims of rights made \n  available for publication and any assurances of licenses to be made \n  available, or the result of an attempt made to obtain a general \n  license or permission for the use of such proprietary rights by \n  implementors or users of this specification, can be obtained from \n  the OASIS Executive Director.\n\n  OASIS invites any interested party to bring to its attention any \n  copyrights, patents or patent applications, or other proprietary \n  rights which may cover technology that may be required to \n  implement this specification. Please address the information to the \n  OASIS Executive Director.\n  \n  This document and translations of it may be copied and furnished to \n  others, and derivative works that comment on or otherwise explain \n  it or assist in its implementation may be prepared, copied, \n  published and distributed, in whole or in part, without restriction of \n  any kind, provided that the above copyright notice and this \n  paragraph are included on all such copies and derivative works. \n  However, this document itself may not be modified in any way, \n  such as by removing the copyright notice or references to OASIS, \n  except as needed for the purpose of developing OASIS \n  specifications, in which case the procedures for copyrights defined \n  in the OASIS Intellectual Property Rights document must be \n  followed, or as required to translate it into languages other than \n  English. \n\n  The limited permissions granted above are perpetual and will not be \n  revoked by OASIS or its successors or assigns. \n\n  This document and the information contained herein is provided on \n  an \"AS IS\" basis and OASIS DISCLAIMS ALL WARRANTIES, \n  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY \n  WARRANTY THAT THE USE OF THE INFORMATION HEREIN \n  WILL NOT INFRINGE ANY RIGHTS OR ANY IMPLIED \n  WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A \n  PARTICULAR PURPOSE.    \n",
  "required": ["TransportProgressStatusRequest"],
  "properties": {
    "_D": {
      "description": "Document ABIE XML namespace string",
      "type": "string"
    },
    "_A": {
      "description": "Library ABIE XML namespace string (for ASBIEs)",
      "type": "string"
    },
    "_B": {
      "description": "BBIE XML namespace string",
      "type": "string"
    },
    "_E": {
      "description": "Extension scaffolding XML namespace string",
      "type": "string"
    },
    "TransportProgressStatusRequest": {
      "description": "A document sent from a transport service provider to a transportation network manager requesting a Transport Progress Status.",
      "$ref": "#/definitions/TransportProgressStatusRequest"
    }
  },
  "additionalProperties": false,
  "type": "object",
  "definitions": {
    "TransportProgressStatusRequest": {
      "title": "Transport Progress Status Request. Details",
      "description": "A document sent from a transport service provider to a transportation network manager requesting a Transport Progress Status.",
      "required": ["ID", "IssueDate", "IssueTime", "TransportMeans"],
      "properties": {
        "UBLExtensions": {
          "title": "UBLExtensions",
          "description": "An optional set of extensions to the committee model",
          "items": {
            "$ref": "../common/UBL-CommonExtensionComponents-2.3.json#/definitions/UBLExtensions"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },

        "UBLVersionID": {
          "title": "Transport Progress Status Request. UBL Version Identifier. Identifier",
          "description": "Identifies the earliest version of the UBL 2 schema for this document type that defines all of the elements that might be encountered in the current instance.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UBLVersionID"
        },
        "CustomizationID": {
          "title": "Transport Progress Status Request. Customization Identifier. Identifier",
          "description": "Identifies a user-defined customization of UBL for a specific use.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CustomizationID"
        },
        "ProfileID": {
          "title": "Transport Progress Status Request. Profile Identifier. Identifier",
          "description": "Identifies a user-defined profile of the customization of UBL being used.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileID"
        },
        "ProfileExecutionID": {
          "title": "Transport Progress Status Request. Profile Execution Identifier. Identifier",
          "description": "Identifies an instance of executing a profile, to associate all transactions in a collaboration.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileExecutionID"
        },
        "ID": {
          "title": "Transport Progress Status Request. Identifier",
          "description": "An identifier for this document, assigned by the sender.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ID"
        },
        "CopyIndicator": {
          "title": "Transport Progress Status Request. Copy_ Indicator. Indicator",
          "description": "Indicates whether this document is a copy (true) or not (false).",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CopyIndicator"
        },
        "UUID": {
          "title": "Transport Progress Status Request. UUID. Identifier",
          "description": "A universally unique identifier for an instance of this document.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UUID"
        },
        "IssueDate": {
          "title": "Transport Progress Status Request. Issue Date. Date",
          "description": "The date, assigned by the sender, on which this document was issued.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueDate"
        },
        "IssueTime": {
          "title": "Transport Progress Status Request. Issue Time. Time",
          "description": "The time, assigned by the sender, at which this document was issued.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueTime"
        },
        "Note": {
          "title": "Transport Progress Status Request. Note. Text",
          "description": "Free-form text pertinent to this document, conveying information that is not contained explicitly in other structures.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/Note"
          },
          "minItems": 1,
          "type": "array"
        },
        "Signature": {
          "title": "Transport Progress Status Request. Signature",
          "description": "A signature applied to this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Signature"
          },
          "minItems": 1,
          "type": "array"
        },
        "SenderParty": {
          "title": "Transport Progress Status Request. Sender_ Party. Party",
          "description": "The party sending the Transport Progress Status Request.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/SenderParty"
        },
        "ReceiverParty": {
          "title": "Transport Progress Status Request. Receiver_ Party. Party",
          "description": "The party receiving the Transport Progress Status Request.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ReceiverParty"
        },
        "TransportMeans": {
          "title": "Transport Progress Status Request. Transport Means",
          "description": "The transport means by which the current transport service is effectuated and for which status is requested.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/TransportMeans"
        },
        "StatusLocation": {
          "title": "Transport Progress Status Request. Status_ Location. Location",
          "description": "A location for which status is requested.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/StatusLocation"
          },
          "minItems": 1,
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object"
    }
  }
}

=== Pratikshit26/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-model/UBL-TransportProgressStatusRequest-2.1-Example.json
{
  "_D": "urn:oasis:names:specification:ubl:schema:xsd:TransportProgressStatusRequest-2",
  "_A": "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
  "_B": "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2",
  "TransportProgressStatusRequest": {
    "UBLVersionID": { "_": "2.1" },
    "ID": { "_": "TPS_1" },
    "IssueDate": { "_": "2011-10-03" },
    "IssueTime": { "_": "14:30:10+01:00" },
    "SenderParty": {
      "PartyIdentification": [
        {
          "ID": {
            "_": "4058673827641",
            "schemeAgencyName": "GS1",
            "schemeName": "GLN"
          }
        }
      ],
      "PartyName": [
        {
          "Name": { "_": "NECOSS" }
        }
      ],
      "Contact": {
        "Name": { "_": "SomeName" },
        "Telephone": { "_": "+49450557000" },
        "ElectronicMail": { "_": "SomeName@necoss.de" }
      }
    },
    "ReceiverParty": {
      "PartyIdentification": [
        {
          "ID": {
            "_": "4058673821325",
            "schemeAgencyName": "GS1",
            "schemeName": "GLN"
          }
        }
      ],
      "PartyName": [
        {
          "Name": { "_": "ARRIVA" }
        }
      ],
      "Contact": {
        "Name": { "_": "SomeName" },
        "Telephone": { "_": "+49450557888" },
        "ElectronicMail": { "_": "SomeName@arriva.de" }
      }
    },
    "TransportMeans": {
      "JourneyID": { "_": "RHamBrem" },
      "RegistrationNationalityID": { "_": "DE" },
      "TransportMeansTypeCode": { "_": "230" },
      "RailTransport": {
        "TrainID": { "_": "RID01235" }
      }
    },
    "StatusLocation": [
      {
        "LocationTypeCode": { "_": "13" },
        "Address": {
          "ID": {
            "_": "4568763527610",
            "schemeAgencyName": "GS1",
            "schemeName": "GLN"
          },
          "StreetName": { "_": "Ludwig-Erhard-Str. 15" },
          "CityName": { "_": "Bremen" },
          "Country": {
            "IdentificationCode": { "_": "DE" }
          }
        }
      }
    ]
  }
}
