=== Pratikshit26/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-schema-model/maindoc/UBL-StockAvailabilityReport-2.3.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "json-schema-model/maindoc/UBL-StockAvailabilityReport-2.3.json",
  "description": "\n  Library:           OASIS Universal Business Language (UBL) 2.3 OS\n                     http://docs.oasis-open.org/ubl/os-UBL-2.3/\n  Release Date:      15 June 2021\n  Module:            json-schema-model/maindoc/UBL-StockAvailabilityReport-2.3.json\n  Generated on:      2021-12-15 21:56z\n  Copyright (c) OASIS Open 2021. All Rights Reserved.\n\n\n  OASIS takes no position regarding the validity or scope of any \n  intellectual property or other rights that might be claimed to pertain \n  to the implementation or use of the technology described in this \n  document or the extent to which any license under such rights \n  might or might not be available; neither does it represent that it has \n  made any effort to identify any such rights. Information on OASIS's \n  procedures with respect to rights in OASIS specifications can be \n  found at the OASIS website. Copies of claims of rights made \n  available for publication and any assurances of licenses to be made \n  available, or the result of an attempt made to obtain a general \n  license or permission for the use of such proprietary rights by \n  implementors or users of this specification, can be obtained from \n  the OASIS Executive Director.\n\n  OASIS invites any interested party to bring to its attention any \n  copyrights, patents or patent applications, or other proprietary \n  rights which may cover technology that may be required to \n  implement this specification. Please address the information to the \n  OASIS Executive Director.\n  \n  This document and translations of it may be copied and furnished to \n  others, and derivative works that comment on or otherwise explain \n  it or assist in its implementation may be prepared, copied, \n  published and distributed, in whole or in part, without restriction of \n  any kind, provided that the above copyright notice and this \n  paragraph are included on all such copies and derivative works. \n  However, this document itself may not be modified in any way, \n  such as by removing the copyright notice or references to OASIS, \n  except as needed for the purpose of developing OASIS \n  specifications, in which case the procedures for copyrights defined \n  in the OASIS Intellectual Property Rights document must be \n  followed, or as required to translate it into languages other than \n  English. \n\n  The limited permissions granted above are perpetual and will not be \n  revoked by OASIS or its successors or assigns. \n\n  This document and the information contained herein is provided on \n  an \"AS IS\" basis and OASIS DISCLAIMS ALL WARRANTIES, \n  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY \n  WARRANTY THAT THE USE OF THE INFORMATION HEREIN \n  WILL NOT INFRINGE ANY RIGHTS OR ANY IMPLIED \n  WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A \n  PARTICULAR PURPOSE.    \n",
  "required": ["StockAvailabilityReport"],
  "properties": {
    "_D": {
      "description": "Document ABIE XML namespace string",
      "type": "string"
    },
    "_A": {
      "description": "Library ABIE XML namespace string (for ASBIEs)",
      "type": "string"
    },
    "_B": {
      "description": "BBIE XML namespace string",
      "type": "string"
    },
    "_E": {
      "description": "Extension scaffolding XML namespace string",
      "type": "string"
    },
    "StockAvailabilityReport": {
      "description": "A report on the quantities of each item that are, or will be, in stock. This document is sent by a Seller (for example a producer) to a Buyer (for example a retailer).",
      "$ref": "#/definitions/StockAvailabilityReport"
    }
  },
  "additionalProperties": false,
  "type": "object",
  "definitions": {
    "StockAvailabilityReport": {
      "title": "Stock Availability Report. Details",
      "description": "A report on the quantities of each item that are, or will be, in stock. This document is sent by a Seller (for example a producer) to a Buyer (for example a retailer).",
      "required": [
        "ID",
        "IssueDate",
        "SellerSupplierParty",
        "InventoryReportingParty",
        "StockAvailabilityReportLine"
      ],
      "properties": {
        "UBLExtensions": {
          "title": "UBLExtensions",
          "description": "An optional set of extensions to the committee model",
          "items": {
            "$ref": "../common/UBL-CommonExtensionComponents-2.3.json#/definitions/UBLExtensions"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },

        "UBLVersionID": {
          "title": "Stock Availability Report. UBL Version Identifier. Identifier",
          "description": "Identifies the earliest version of the UBL 2 schema for this document type that defines all of the elements that might be encountered in the current instance.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UBLVersionID"
        },
        "CustomizationID": {
          "title": "Stock Availability Report. Customization Identifier. Identifier",
          "description": "Identifies a user-defined customization of UBL for a specific use.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CustomizationID"
        },
        "ProfileID": {
          "title": "Stock Availability Report. Profile Identifier. Identifier",
          "description": "Identifies a user-defined profile of the customization of UBL being used.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileID"
        },
        "ProfileExecutionID": {
          "title": "Stock Availability Report. Profile Execution Identifier. Identifier",
          "description": "Identifies an instance of executing a profile, to associate all transactions in a collaboration.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileExecutionID"
        },
        "ID": {
          "title": "Stock Availability Report. Identifier",
          "description": "An identifier for this document, assigned by the sender.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ID"
        },
        "CopyIndicator": {
          "title": "Stock Availability Report. Copy_ Indicator. Indicator",
          "description": "Indicates whether this document is a copy (true) or not (false).",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CopyIndicator"
        },
        "UUID": {
          "title": "Stock Availability Report. UUID. Identifier",
          "description": "A universally unique identifier for an instance of this document.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UUID"
        },
        "IssueDate": {
          "title": "Stock Availability Report. Issue Date. Date",
          "description": "The date, assigned by the sender, on which this document was issued.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueDate"
        },
        "IssueTime": {
          "title": "Stock Availability Report. Issue Time. Time",
          "description": "The time, assigned by the sender, at which this document was issued.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueTime"
        },
        "Note": {
          "title": "Stock Availability Report. Note. Text",
          "description": "Free-form text pertinent to this document, conveying information that is not contained explicitly in other structures.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/Note"
          },
          "minItems": 1,
          "type": "array"
        },
        "DocumentCurrencyCode": {
          "title": "Stock Availability Report. Document_ Currency Code. Code",
          "description": "A code signifying the default currency for this document.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/DocumentCurrencyCode"
        },
        "InventoryPeriod": {
          "title": "Stock Availability Report. Inventory_ Period. Period",
          "description": "The inventory period covered by the Report.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/InventoryPeriod"
        },
        "DocumentReference": {
          "title": "Stock Availability Report. Document Reference",
          "description": "A reference to another document associated with this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/DocumentReference"
          },
          "minItems": 1,
          "type": "array"
        },
        "Signature": {
          "title": "Stock Availability Report. Signature",
          "description": "A signature applied to this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Signature"
          },
          "minItems": 1,
          "type": "array"
        },
        "SellerSupplierParty": {
          "title": "Stock Availability Report. Seller_ Supplier Party. Supplier Party",
          "description": "The seller.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/SellerSupplierParty"
        },
        "RetailerCustomerParty": {
          "title": "Stock Availability Report. Retailer_ Customer Party. Customer Party",
          "description": "The retailer.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/RetailerCustomerParty"
        },
        "InventoryReportingParty": {
          "title": "Stock Availability Report. Inventory Reporting_ Party. Party",
          "description": "The party that will receive and use the Stock Availability Report (normally the branch for which the stock is reported).",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/InventoryReportingParty"
        },
        "StockAvailabilityReportLine": {
          "title": "Stock Availability Report. Stock Availability Report Line",
          "description": "A line representing a particular item of sale and associated with a line in the Catalogue.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/StockAvailabilityReportLine"
          },
          "minItems": 1,
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object"
    }
  }
}

=== Pratikshit26/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-model/UBL-StockAvailabilityReport-2.1-Example.json
{
  "_D": "urn:oasis:names:specification:ubl:schema:xsd:StockAvailabilityReport-2",
  "_A": "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
  "_B": "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2",
  "StockAvailabilityReport": {
    "UBLVersionID": { "_": "2.1" },
    "ID": { "_": "SA2009" },
    "CopyIndicator": { "_": false },
    "IssueDate": { "_": "2010-04-11" },
    "Note": [
      {
        "_": "Report about quantities of each item which are (or will be) available"
      }
    ],
    "InventoryPeriod": {
      "StartDate": { "_": "2010-04-11" },
      "StartTime": { "_": "08:00:00Z" },
      "EndDate": { "_": "2011-04-11" }
    },
    "SellerSupplierParty": {
      "Party": {
        "PartyName": [
          {
            "Name": { "_": "Arancio Forniture spa" }
          }
        ],
        "PostalAddress": {
          "StreetName": { "_": "Via Dell'Arcoveggio" },
          "BuildingNumber": { "_": "403" },
          "CityName": { "_": "Bologna" },
          "PostalZone": { "_": "40129" },
          "Country": {
            "IdentificationCode": { "_": "IT" },
            "Name": { "_": "Italy" }
          }
        },
        "Contact": {
          "Name": { "_": "Mr Rossi" },
          "Telephone": { "_": "0039 051 23000000" },
          "Telefax": { "_": "0039 051 23000023" },
          "ElectronicMail": { "_": "rossi@arancioforniture.it" }
        }
      }
    },
    "RetailerCustomerParty": {
      "Party": {
        "PartyName": [
          {
            "Name": { "_": "Beta Shop" }
          }
        ],
        "PostalAddress": {
          "StreetName": { "_": "Via Emilia" },
          "BuildingNumber": { "_": "1" },
          "CityName": { "_": "Modena" },
          "PostalZone": { "_": "41121" },
          "Country": {
            "IdentificationCode": { "_": "IT" },
            "Name": { "_": "Italy" }
          }
        },
        "Contact": {
          "Name": { "_": "Mr Delta" },
          "Telephone": { "_": "0039 059 33000000" },
          "Telefax": { "_": "0039 059 33000055" },
          "ElectronicMail": { "_": "delta@betashop.it" }
        }
      }
    },
    "InventoryReportingParty": {
      "PartyName": [
        {
          "Name": { "_": "Beta Shop" }
        }
      ],
      "PostalAddress": {
        "Floor": { "_": "2" },
        "Room": { "_": "309" },
        "StreetName": { "_": "Via Emilia" },
        "BuildingNumber": { "_": "1" },
        "CityName": { "_": "Modena" },
        "PostalZone": { "_": "41121" },
        "Country": {
          "IdentificationCode": { "_": "IT" },
          "Name": { "_": "Italy" }
        }
      },
      "Contact": {
        "Name": { "_": "Mr Gamma" },
        "Telephone": { "_": "0039 059 33000022" },
        "Telefax": { "_": "0039 059 33000057" },
        "ElectronicMail": { "_": "gamma@betashop.it" }
      }
    },
    "StockAvailabilityReportLine": [
      {
        "ID": { "_": "1" },
        "Quantity": { "_": 50, "unitCode": "NAR" },
        "AvailabilityDate": { "_": "2010-04-20" },
        "AvailabilityStatusCode": {
          "_": "1",
          "listID": "7011",
          "listAgencyName": "UN/ECE",
          "listURI": "http://www.unece.org/trade/untdid/d09b/tred/tred7011.htm"
        },
        "Item": {
          "Description": [{ "_": "T-shirt" }],
          "BuyersItemIdentification": {
            "ID": { "_": "TT319" }
          },
          "SellersItemIdentification": {
            "ID": { "_": "ZZ738" }
          }
        }
      },
      {
        "ID": { "_": "2" },
        "Quantity": { "_": 80, "unitCode": "NAR" },
        "AvailabilityDate": { "_": "2010-04-11" },
        "AvailabilityStatusCode": {
          "_": "2",
          "listID": "7011",
          "listAgencyName": "UN/ECE",
          "listURI": "http://www.unece.org/trade/untdid/d09b/tred/tred7011.htm"
        },
        "Item": {
          "Description": [{ "_": "jersey" }],
          "BuyersItemIdentification": {
            "ID": { "_": "TJ043" }
          },
          "SellersItemIdentification": {
            "ID": { "_": "K0058" }
          }
        }
      },
      {
        "ID": { "_": "3" },
        "Quantity": { "_": 0, "unitCode": "NAR" },
        "AvailabilityStatusCode": {
          "_": "8",
          "listID": "7011",
          "listAgencyName": "UN/ECE",
          "listURI": "http://www.unece.org/trade/untdid/d09b/tred/tred7011.htm"
        },
        "Item": {
          "Description": [{ "_": "skirt" }],
          "BuyersItemIdentification": {
            "ID": { "_": "TS893" }
          },
          "SellersItemIdentification": {
            "ID": { "_": "PK009" }
          }
        }
      }
    ]
  }
}
