=== Pratikshit26/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-schema-model/maindoc/UBL-TransportExecutionPlanRequest-2.3.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "json-schema-model/maindoc/UBL-TransportExecutionPlanRequest-2.3.json",
  "description": "\n  Library:           OASIS Universal Business Language (UBL) 2.3 OS\n                     http://docs.oasis-open.org/ubl/os-UBL-2.3/\n  Release Date:      15 June 2021\n  Module:            json-schema-model/maindoc/UBL-TransportExecutionPlanRequest-2.3.json\n  Generated on:      2021-12-15 21:56z\n  Copyright (c) OASIS Open 2021. All Rights Reserved.\n\n\n  OASIS takes no position regarding the validity or scope of any \n  intellectual property or other rights that might be claimed to pertain \n  to the implementation or use of the technology described in this \n  document or the extent to which any license under such rights \n  might or might not be available; neither does it represent that it has \n  made any effort to identify any such rights. Information on OASIS's \n  procedures with respect to rights in OASIS specifications can be \n  found at the OASIS website. Copies of claims of rights made \n  available for publication and any assurances of licenses to be made \n  available, or the result of an attempt made to obtain a general \n  license or permission for the use of such proprietary rights by \n  implementors or users of this specification, can be obtained from \n  the OASIS Executive Director.\n\n  OASIS invites any interested party to bring to its attention any \n  copyrights, patents or patent applications, or other proprietary \n  rights which may cover technology that may be required to \n  implement this specification. Please address the information to the \n  OASIS Executive Director.\n  \n  This document and translations of it may be copied and furnished to \n  others, and derivative works that comment on or otherwise explain \n  it or assist in its implementation may be prepared, copied, \n  published and distributed, in whole or in part, without restriction of \n  any kind, provided that the above copyright notice and this \n  paragraph are included on all such copies and derivative works. \n  However, this document itself may not be modified in any way, \n  such as by removing the copyright notice or references to OASIS, \n  except as needed for the purpose of developing OASIS \n  specifications, in which case the procedures for copyrights defined \n  in the OASIS Intellectual Property Rights document must be \n  followed, or as required to translate it into languages other than \n  English. \n\n  The limited permissions granted above are perpetual and will not be \n  revoked by OASIS or its successors or assigns. \n\n  This document and the information contained herein is provided on \n  an \"AS IS\" basis and OASIS DISCLAIMS ALL WARRANTIES, \n  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY \n  WARRANTY THAT THE USE OF THE INFORMATION HEREIN \n  WILL NOT INFRINGE ANY RIGHTS OR ANY IMPLIED \n  WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A \n  PARTICULAR PURPOSE.    \n",
  "required": ["TransportExecutionPlanRequest"],
  "properties": {
    "_D": {
      "description": "Document ABIE XML namespace string",
      "type": "string"
    },
    "_A": {
      "description": "Library ABIE XML namespace string (for ASBIEs)",
      "type": "string"
    },
    "_B": {
      "description": "BBIE XML namespace string",
      "type": "string"
    },
    "_E": {
      "description": "Extension scaffolding XML namespace string",
      "type": "string"
    },
    "TransportExecutionPlanRequest": {
      "description": "A document sent by a transport user to request a transport service from a transport service provider.",
      "$ref": "#/definitions/TransportExecutionPlanRequest"
    }
  },
  "additionalProperties": false,
  "type": "object",
  "definitions": {
    "TransportExecutionPlanRequest": {
      "title": "Transport Execution Plan Request. Details",
      "description": "A document sent by a transport user to request a transport service from a transport service provider.",
      "required": [
        "ID",
        "TransportUserParty",
        "TransportServiceProviderParty",
        "Consignment"
      ],
      "properties": {
        "UBLExtensions": {
          "title": "UBLExtensions",
          "description": "An optional set of extensions to the committee model",
          "items": {
            "$ref": "../common/UBL-CommonExtensionComponents-2.3.json#/definitions/UBLExtensions"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },

        "UBLVersionID": {
          "title": "Transport Execution Plan Request. UBL Version Identifier. Identifier",
          "description": "Identifies the earliest version of the UBL 2 schema for this document type that defines all of the elements that might be encountered in the current instance.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UBLVersionID"
        },
        "CustomizationID": {
          "title": "Transport Execution Plan Request. Customization Identifier. Identifier",
          "description": "Identifies a user-defined customization of UBL for a specific use.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CustomizationID"
        },
        "ProfileID": {
          "title": "Transport Execution Plan Request. Profile Identifier. Identifier",
          "description": "Identifies a user-defined profile of the customization of UBL being used.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileID"
        },
        "ProfileExecutionID": {
          "title": "Transport Execution Plan Request. Profile Execution Identifier. Identifier",
          "description": "Identifies an instance of executing a profile, to associate all transactions in a collaboration.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileExecutionID"
        },
        "ID": {
          "title": "Transport Execution Plan Request. Identifier",
          "description": "An identifier for this document, assigned by the sender.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ID"
        },
        "VersionID": {
          "title": "Transport Execution Plan Request. Version. Identifier",
          "description": "An identifier for the current version of the Transport Execution Plan Request.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/VersionID"
        },
        "CopyIndicator": {
          "title": "Transport Execution Plan Request. Copy_ Indicator. Indicator",
          "description": "Indicates whether this document is a copy (true) or not (false).",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CopyIndicator"
        },
        "UUID": {
          "title": "Transport Execution Plan Request. UUID. Identifier",
          "description": "A universally unique identifier for an instance of this document.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UUID"
        },
        "IssueDate": {
          "title": "Transport Execution Plan Request. Issue Date. Date",
          "description": "The date, assigned by the sender, on which this document was issued.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueDate"
        },
        "IssueTime": {
          "title": "Transport Execution Plan Request. Issue Time. Time",
          "description": "The time, assigned by the sender, at which this document was issued.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueTime"
        },
        "DocumentStatusCode": {
          "title": "Transport Execution Plan Request. Document Status Code. Code",
          "description": "A code signifying the status of the Transport Execution Plan Request.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/DocumentStatusCode"
        },
        "DocumentStatusReasonCode": {
          "title": "Transport Execution Plan Request. Document Status Reason Code. Code",
          "description": "A code signifying a reason associated with the status of the Transport Execution Plan Request.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/DocumentStatusReasonCode"
        },
        "DocumentStatusReasonDescription": {
          "title": "Transport Execution Plan Request. Document Status Reason Description. Text",
          "description": "A reason associated with the status of the Transport Execution Plan Request.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/DocumentStatusReasonDescription"
          },
          "minItems": 1,
          "type": "array"
        },
        "Note": {
          "title": "Transport Execution Plan Request. Note. Text",
          "description": "Free-form text pertinent to this document, conveying information that is not contained explicitly in other structures.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/Note"
          },
          "minItems": 1,
          "type": "array"
        },
        "TransportUserRemarks": {
          "title": "Transport Execution Plan Request. Transport User_ Remarks. Text",
          "description": "Remarks from the transport user regarding the transport operations referenced in the Transport Execution Plan Request.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/TransportUserRemarks"
          },
          "minItems": 1,
          "type": "array"
        },
        "SenderParty": {
          "title": "Transport Execution Plan Request. Sender_ Party. Party",
          "description": "The party sending the Transport Execution Plan Request.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/SenderParty"
        },
        "ReceiverParty": {
          "title": "Transport Execution Plan Request. Receiver_ Party. Party",
          "description": "The party receiving the Transport Execution Plan Request.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ReceiverParty"
        },
        "TransportUserParty": {
          "title": "Transport Execution Plan Request. Transport User_ Party. Party",
          "description": "The party requesting the transport services referenced in the Transport Execution Plan Request.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/TransportUserParty"
        },
        "TransportServiceProviderParty": {
          "title": "Transport Execution Plan Request. Transport Service Provider_ Party. Party",
          "description": "The party providing the transport services referenced in the Transport Execution Plan Request.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/TransportServiceProviderParty"
        },
        "PayeeParty": {
          "title": "Transport Execution Plan Request. Payee_ Party. Party",
          "description": "The party that will pay for the transport service(s) referred to in a Transport Execution Plan.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/PayeeParty"
        },
        "Signature": {
          "title": "Transport Execution Plan Request. Signature",
          "description": "A signature applied to this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Signature"
          },
          "minItems": 1,
          "type": "array"
        },
        "TransportExecutionPlanDocumentReference": {
          "title": "Transport Execution Plan Request. Transport Execution Plan_ Document Reference. Document Reference",
          "description": "A reference to an original Transport Execution Plan Document.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/TransportExecutionPlanDocumentReference"
        },
        "TransportServiceDescriptionDocumentReference": {
          "title": "Transport Execution Plan Request. Transport Service Description_ Document Reference. Document Reference",
          "description": "A reference to the Transport Service Description, which is used by a transport service provider to announce transport services to transport users (buyers).",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/TransportServiceDescriptionDocumentReference"
        },
        "AdditionalDocumentReference": {
          "title": "Transport Execution Plan Request. Additional_ Document Reference. Document Reference",
          "description": "A reference to an additional document associated with this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AdditionalDocumentReference"
          },
          "minItems": 1,
          "type": "array"
        },
        "TransportContract": {
          "title": "Transport Execution Plan Request. Transport_ Contract. Contract",
          "description": "A potential contract related to the Transport Execution Plan Request.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/TransportContract"
        },
        "TransportServiceProviderResponseDeadlinePeriod": {
          "title": "Transport Execution Plan Request. Transport Service Provider Response Deadline_ Period. Period",
          "description": "A deadline for a response from the Transport Service Provider to this Transport Execution Plan Request.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/TransportServiceProviderResponseDeadlinePeriod"
          },
          "minItems": 1,
          "type": "array"
        },
        "MainTransportationService": {
          "title": "Transport Execution Plan Request. Main_ Transportation Service. Transportation Service",
          "description": "A description of the main transportation service referenced in the Transport Execution Plan Request.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/MainTransportationService"
        },
        "AdditionalTransportationService": {
          "title": "Transport Execution Plan Request. Additional_ Transportation Service. Transportation Service",
          "description": "A description of an additional transportation service referenced in the Transport Execution Plan Request.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AdditionalTransportationService"
          },
          "minItems": 1,
          "type": "array"
        },
        "ServiceStartTimePeriod": {
          "title": "Transport Execution Plan Request. Service Start Time_ Period. Period",
          "description": "The period within which the services referred to in the Transport Execution Plan Request must begin.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ServiceStartTimePeriod"
        },
        "ServiceEndTimePeriod": {
          "title": "Transport Execution Plan Request. Service End Time_ Period. Period",
          "description": "The period during which the services referred to in the Transport Execution Plan Request must be completed.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ServiceEndTimePeriod"
        },
        "FromLocation": {
          "title": "Transport Execution Plan Request. From_ Location. Location",
          "description": "The location of origin of the transport service referenced in the Transport Execution Plan Request.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/FromLocation"
        },
        "ToLocation": {
          "title": "Transport Execution Plan Request. To_ Location. Location",
          "description": "The destination location for the transport service referenced in the Transport Execution Plan Request.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ToLocation"
        },
        "AtLocation": {
          "title": "Transport Execution Plan Request. At_ Location. Location",
          "description": "The location of a transport service (e.g., terminal handling service) that does not require transport movement.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AtLocation"
        },
        "TransportExecutionTerms": {
          "title": "Transport Execution Plan Request. Transport Execution Terms",
          "description": "A description of terms and conditions related to the Transport Execution Plan Request.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/TransportExecutionTerms"
        },
        "Consignment": {
          "title": "Transport Execution Plan Request. Consignment",
          "description": "A description of an identifiable collection of goods items to be transported between the consignor and the consignee. This information may be defined within a transport contract. A consignment may comprise more than one shipment (e.g., when consolidated by a freight forwarder).",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Consignment"
          },
          "minItems": 1,
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object"
    }
  }
}

=== Pratikshit26/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-model/UBL-TransportExecutionPlanRequest-2.1-Example.json
{
  "_D": "urn:oasis:names:specification:ubl:schema:xsd:TransportExecutionPlanRequest-2",
  "_A": "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
  "_B": "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2",
  "TransportExecutionPlanRequest": {
    "UBLVersionID": { "_": "2.1" },
    "ID": { "_": "TEPR_1" },
    "VersionID": { "_": "1" },
    "IssueDate": { "_": "2011-09-13" },
    "IssueTime": { "_": "10:00:10+01:00" },
    "DocumentStatusCode": { "_": "NotConfirmed" },
    "SenderParty": {
      "PartyIdentification": [
        {
          "ID": {
            "_": "4058673827000",
            "schemeAgencyName": "GS1",
            "schemeName": "GLN"
          }
        }
      ],
      "PartyName": [
        {
          "Name": { "_": "Consignor" }
        }
      ],
      "Contact": {
        "Name": { "_": "SomeName" },
        "Telephone": { "_": "+8687878763" },
        "ElectronicMail": { "_": "SomeName@consignor.cn" }
      }
    },
    "ReceiverParty": {
      "PartyIdentification": [
        {
          "ID": {
            "_": "4058673827641",
            "schemeAgencyName": "GS1",
            "schemeName": "GLN"
          }
        }
      ],
      "PartyName": [
        {
          "Name": { "_": "NECOSS" }
        }
      ],
      "Contact": {
        "Name": { "_": "SomeName" },
        "Telephone": { "_": "+49450557000" },
        "ElectronicMail": { "_": "SomeName@necoss.de" }
      }
    },
    "TransportUserParty": {
      "PartyIdentification": [
        {
          "ID": {
            "_": "4058673827000",
            "schemeAgencyName": "GS1",
            "schemeName": "GLN"
          }
        }
      ],
      "PartyName": [
        {
          "Name": { "_": "Consignor" }
        }
      ],
      "Contact": {
        "Name": { "_": "SomeName" },
        "Telephone": { "_": "+8687878763" },
        "ElectronicMail": { "_": "SomeName@consignor.cn" }
      }
    },
    "TransportServiceProviderParty": {
      "PartyIdentification": [
        {
          "ID": {
            "_": "4058673827641",
            "schemeAgencyName": "GS1",
            "schemeName": "GLN"
          }
        }
      ],
      "PartyName": [
        {
          "Name": { "_": "NECOSS" }
        }
      ],
      "Contact": {
        "Name": { "_": "SomeName" },
        "Telephone": { "_": "+49450557000" },
        "ElectronicMail": { "_": "SomeName@necoss.de" }
      }
    },
    "TransportServiceDescriptionDocumentReference": {
      "ID": { "_": "2" }
    },
    "TransportContract": {
      "Note": [{ "_": "Framework Agreement" }],
      "ContractDocumentReference": [
        {
          "ID": { "_": "TC101" },
          "IssueDate": { "_": "2010-01-01" },
          "DocumentTypeCode": { "_": "315" },
          "DocumentType": [{ "_": "Contract" }],
          "DocumentDescription": [
            { "_": "Framework Agreement between Consignor and NECOSS" }
          ]
        }
      ]
    },
    "TransportServiceProviderResponseDeadlinePeriod": [
      {
        "EndDate": { "_": "2011-09-13" },
        "EndTime": { "_": "11:00:10+01:00" }
      }
    ],
    "MainTransportationService": {
      "TransportServiceCode": { "_": "3" },
      "TransportationServiceDescription": [
        { "_": "Transport from Hamburg to Nurnberg" }
      ]
    },
    "ServiceEndTimePeriod": {
      "EndDate": { "_": "2011-10-06" },
      "EndTime": { "_": "16:00:10+01:00" }
    },
    "FromLocation": {
      "LocationTypeCode": { "_": "13" },
      "Address": {
        "ID": {
          "_": "DEHAM",
          "schemeAgencyName": "UN",
          "schemeName": "UN/LOCODE"
        },
        "StreetName": { "_": "Neuer Wandrahm 4" },
        "CityName": { "_": "Hamburg" },
        "PostalZone": { "_": "29400" },
        "Country": {
          "IdentificationCode": { "_": "DE" }
        }
      }
    },
    "ToLocation": {
      "LocationTypeCode": { "_": "7" },
      "Address": {
        "StreetName": { "_": "Grosse strasse 34" },
        "CityName": { "_": "Nurnberg" },
        "PostalZone": { "_": "28400" },
        "Country": {
          "IdentificationCode": { "_": "DE" }
        }
      }
    },
    "TransportExecutionTerms": {
      "DeliveryTerms": [
        {
          "ID": { "_": "EXW", "schemeAgencyName": "INCOTERMS" },
          "DeliveryLocation": {
            "Address": {
              "CityName": { "_": "Hamburg" }
            }
          }
        }
      ],
      "NotificationRequirement": [
        {
          "NotificationTypeCode": { "_": "TIME_SCHEDULE_DEVIATIONS" },
          "NotifyParty": [
            {
              "EndpointID": { "_": "www.consignee.de/statusnotifications/" },
              "PartyName": [
                {
                  "Name": { "_": "Consignee" }
                }
              ],
              "Contact": {
                "ElectronicMail": { "_": "someName@consignee.de" }
              }
            },
            {
              "EndpointID": { "_": "www.consignor.cn/statusnotifications/" },
              "PartyName": [
                {
                  "Name": { "_": "Consignor" }
                }
              ],
              "Contact": {
                "ElectronicMail": { "_": "someName@consignor.cn" }
              }
            }
          ]
        },
        {
          "NotificationTypeCode": { "_": "ITEM_CONDITION_DEVIATIONS" },
          "PostEventNotificationDurationMeasure": {
            "_": 10,
            "unitCode": "MIN"
          },
          "NotifyParty": [
            {
              "EndpointID": { "_": "www.consignee.com/statusnotifications/" },
              "PartyName": [
                {
                  "Name": { "_": "Consignee" }
                }
              ],
              "Contact": {
                "ElectronicMail": { "_": "someName@consignee.de" }
              }
            },
            {
              "EndpointID": { "_": "www.consignor.cn/statusnotifications/" },
              "PartyName": [
                {
                  "Name": { "_": "Consignor" }
                }
              ],
              "Contact": {
                "ElectronicMail": { "_": "someName@consignor.cn" }
              }
            }
          ]
        }
      ]
    },
    "Consignment": [
      {
        "ID": { "_": "CON_1" },
        "GrossWeightMeasure": { "_": 50000, "unitCode": "KGM" },
        "NetWeightMeasure": { "_": 3000, "unitCode": "KGM" },
        "GrossVolumeMeasure": { "_": 78, "unitCode": "MTQ" },
        "LoadingLengthMeasure": { "_": 12, "unitCode": "MTR" },
        "HazardousRiskIndicator": { "_": false },
        "TotalTransportHandlingUnitQuantity": { "_": 2 },
        "ConsolidatedShipment": [
          {
            "ID": { "_": "GSIN_1" }
          },
          {
            "ID": { "_": "GSIN_2" }
          }
        ],
        "RequestedPickupTransportEvent": {
          "Location": {
            "Address": {
              "ID": {
                "_": "DEHAM",
                "schemeAgencyName": "UN",
                "schemeName": "UN/LOCODE"
              },
              "StreetName": { "_": "Neuer Wandrahm 4" },
              "CityName": { "_": "Hamburg" },
              "PostalZone": { "_": "29400" },
              "Country": {
                "IdentificationCode": { "_": "DE" }
              }
            }
          },
          "Period": [
            {
              "StartDate": { "_": "2011-10-03" },
              "StartTime": { "_": "09:30:10+01:00" },
              "EndDate": { "_": "2011-10-03" },
              "EndTime": { "_": "12:30:10+01:00" }
            }
          ]
        },
        "RequestedDeliveryTransportEvent": {
          "Location": {
            "Address": {
              "StreetName": { "_": "Grosse strasse 34" },
              "CityName": { "_": "Nurnberg" },
              "PostalZone": { "_": "28400" },
              "Country": {
                "IdentificationCode": { "_": "DE" }
              }
            }
          },
          "Period": [
            {
              "StartDate": { "_": "2011-10-06" },
              "StartTime": { "_": "12:30:10+01:00" },
              "EndDate": { "_": "2011-10-06" },
              "EndTime": { "_": "15:30:10+01:00" }
            }
          ]
        },
        "ConsigneeParty": {
          "PartyIdentification": [
            {
              "ID": {
                "_": "4058673827123",
                "schemeAgencyName": "GS1",
                "schemeName": "GLN"
              }
            }
          ],
          "PartyName": [
            {
              "Name": { "_": "Consignee" }
            }
          ],
          "Contact": {
            "Name": { "_": "SomeName" },
            "Telephone": { "_": "+4987878763" },
            "ElectronicMail": { "_": "SomeName@consignee.de" }
          }
        },
        "ConsignorParty": {
          "PartyIdentification": [
            {
              "ID": {
                "_": "4058673827000",
                "schemeAgencyName": "GS1",
                "schemeName": "GLN"
              }
            }
          ],
          "PartyName": [
            {
              "Name": { "_": "Consignor" }
            }
          ],
          "PostalAddress": {
            "ID": {
              "_": "4058673827000",
              "schemeAgencyName": "GS1",
              "schemeName": "GLN"
            }
          },
          "Contact": {
            "Name": { "_": "SomeName" },
            "Telephone": { "_": "+8676576456" },
            "ElectronicMail": { "_": "SomeName@consignor.cn" }
          }
        },
        "OriginalDepartureCountry": {
          "IdentificationCode": { "_": "CN" }
        },
        "FinalDestinationCountry": {
          "IdentificationCode": { "_": "DE" }
        },
        "TransportHandlingUnit": [
          {
            "ID": { "_": "CON_THU_1" },
            "TransportHandlingUnitTypeCode": { "_": "4" },
