=== Pratikshit26/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-schema-legacy/maindoc/UBL-Reminder-2.3.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "json-schema-legacy/maindoc/UBL-Reminder-2.3.json",
  "description": "\n  Library:           OASIS Universal Business Language (UBL) 2.3 OS\n                     http://docs.oasis-open.org/ubl/os-UBL-2.3/\n  Release Date:      15 June 2021\n  Module:            json-schema-legacy/maindoc/UBL-Reminder-2.3.json\n  Generated on:      2021-12-15 21:56z\n  Copyright (c) OASIS Open 2021. All Rights Reserved.\n\n\n  OASIS takes no position regarding the validity or scope of any \n  intellectual property or other rights that might be claimed to pertain \n  to the implementation or use of the technology described in this \n  document or the extent to which any license under such rights \n  might or might not be available; neither does it represent that it has \n  made any effort to identify any such rights. Information on OASIS's \n  procedures with respect to rights in OASIS specifications can be \n  found at the OASIS website. Copies of claims of rights made \n  available for publication and any assurances of licenses to be made \n  available, or the result of an attempt made to obtain a general \n  license or permission for the use of such proprietary rights by \n  implementors or users of this specification, can be obtained from \n  the OASIS Executive Director.\n\n  OASIS invites any interested party to bring to its attention any \n  copyrights, patents or patent applications, or other proprietary \n  rights which may cover technology that may be required to \n  implement this specification. Please address the information to the \n  OASIS Executive Director.\n  \n  This document and translations of it may be copied and furnished to \n  others, and derivative works that comment on or otherwise explain \n  it or assist in its implementation may be prepared, copied, \n  published and distributed, in whole or in part, without restriction of \n  any kind, provided that the above copyright notice and this \n  paragraph are included on all such copies and derivative works. \n  However, this document itself may not be modified in any way, \n  such as by removing the copyright notice or references to OASIS, \n  except as needed for the purpose of developing OASIS \n  specifications, in which case the procedures for copyrights defined \n  in the OASIS Intellectual Property Rights document must be \n  followed, or as required to translate it into languages other than \n  English. \n\n  The limited permissions granted above are perpetual and will not be \n  revoked by OASIS or its successors or assigns. \n\n  This document and the information contained herein is provided on \n  an \"AS IS\" basis and OASIS DISCLAIMS ALL WARRANTIES, \n  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY \n  WARRANTY THAT THE USE OF THE INFORMATION HEREIN \n  WILL NOT INFRINGE ANY RIGHTS OR ANY IMPLIED \n  WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A \n  PARTICULAR PURPOSE.    \n",
  "required": ["Reminder"],
  "properties": {
    "_D": {
      "description": "Document ABIE XML namespace string",
      "type": "string"
    },
    "_A": {
      "description": "Library ABIE XML namespace string (for ASBIEs)",
      "type": "string"
    },
    "_B": {
      "description": "BBIE XML namespace string",
      "type": "string"
    },
    "_E": {
      "description": "Extension scaffolding XML namespace string",
      "type": "string"
    },
    "Reminder": {
      "description": "A document used to remind a customer of payments past due.",
      "items": {
        "$ref": "#/definitions/Reminder"
      },
      "maxItems": 1,
      "minItems": 1,
      "type": "array"
    }
  },
  "additionalProperties": false,
  "type": "object",
  "definitions": {
    "Reminder": {
      "title": "Reminder. Details",
      "description": "A document used to remind a customer of payments past due.",
      "required": [
        "ID",
        "IssueDate",
        "AccountingSupplierParty",
        "AccountingCustomerParty",
        "LegalMonetaryTotal",
        "ReminderLine"
      ],
      "properties": {
        "UBLExtensions": {
          "title": "UBLExtensions",
          "description": "An optional set of extensions to the committee model",
          "items": {
            "$ref": "../common/UBL-CommonExtensionComponents-2.3.json#/definitions/UBLExtensions"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },

        "UBLVersionID": {
          "title": "Reminder. UBL Version Identifier. Identifier",
          "description": "Identifies the earliest version of the UBL 2 schema for this document type that defines all of the elements that might be encountered in the current instance.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UBLVersionID"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "CustomizationID": {
          "title": "Reminder. Customization Identifier. Identifier",
          "description": "Identifies a user-defined customization of UBL for a specific use.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CustomizationID"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "ProfileID": {
          "title": "Reminder. Profile Identifier. Identifier",
          "description": "Identifies a user-defined profile of the customization of UBL being used.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileID"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "ProfileExecutionID": {
          "title": "Reminder. Profile Execution Identifier. Identifier",
          "description": "Identifies an instance of executing a profile, to associate all transactions in a collaboration.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileExecutionID"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "ID": {
          "title": "Reminder. Identifier",
          "description": "An identifier for this document, assigned by the sender.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ID"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "CopyIndicator": {
          "title": "Reminder. Copy_ Indicator. Indicator",
          "description": "Indicates whether this document is a copy (true) or not (false).",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CopyIndicator"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "UUID": {
          "title": "Reminder. UUID. Identifier",
          "description": "A universally unique identifier for an instance of this document.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UUID"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "IssueDate": {
          "title": "Reminder. Issue Date. Date",
          "description": "The date, assigned by the sender, on which this document was issued.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueDate"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "IssueTime": {
          "title": "Reminder. Issue Time. Time",
          "description": "The time, assigned by the sender, at which this document was issued.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueTime"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "ReminderTypeCode": {
          "title": "Reminder. Reminder Type Code. Code",
          "description": "A code signifying the type of the Reminder.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ReminderTypeCode"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "ReminderSequenceNumeric": {
          "title": "Reminder. Reminder Sequence. Numeric",
          "description": "The number of the current Reminder in the sequence of reminders relating to the specified payments; the number of reminders previously sent plus one.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ReminderSequenceNumeric"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "Note": {
          "title": "Reminder. Note. Text",
          "description": "Free-form text pertinent to this document, conveying information that is not contained explicitly in other structures.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/Note"
          },
          "minItems": 1,
          "type": "array"
        },
        "TaxPointDate": {
          "title": "Reminder. Tax Point Date. Date",
          "description": "The date of the Reminder, used to indicate the point at which tax becomes applicable.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/TaxPointDate"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "DocumentCurrencyCode": {
          "title": "Reminder. Document_ Currency Code. Code",
          "description": "A code signifying the default currency for this document.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/DocumentCurrencyCode"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "TaxCurrencyCode": {
          "title": "Reminder. Tax_ Currency Code. Code",
          "description": "A code signifying the currency used for tax amounts in the Reminder.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/TaxCurrencyCode"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "PricingCurrencyCode": {
          "title": "Reminder. Pricing_ Currency Code. Code",
          "description": "A code signifying the currency used for prices in the Reminder.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/PricingCurrencyCode"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "PaymentCurrencyCode": {
          "title": "Reminder. Payment_ Currency Code. Code",
          "description": "A code signifying the currency used for payment in the Reminder.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/PaymentCurrencyCode"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "PaymentAlternativeCurrencyCode": {
          "title": "Reminder. Payment Alternative_ Currency Code. Code",
          "description": "A code signifying the alternative currency used for payment in the Reminder.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/PaymentAlternativeCurrencyCode"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "AccountingCostCode": {
          "title": "Reminder. Accounting Cost Code. Code",
          "description": "The buyer's accounting code, applied to the Reminder as a whole.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/AccountingCostCode"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "AccountingCost": {
          "title": "Reminder. Accounting Cost. Text",
          "description": "The buyer's accounting code, applied to the Reminder as a whole, expressed as text.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/AccountingCost"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "LineCountNumeric": {
          "title": "Reminder. Line Count. Numeric",
          "description": "The number of Reminder Lines in this document.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/LineCountNumeric"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "ReminderPeriod": {
          "title": "Reminder. Reminder_ Period. Period",
          "description": "The periods to which the Reminder applies.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ReminderPeriod"
          },
          "minItems": 1,
          "type": "array"
        },
        "AdditionalDocumentReference": {
          "title": "Reminder. Additional_ Document Reference. Document Reference",
          "description": "A reference to an additional document associated with this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AdditionalDocumentReference"
          },
          "minItems": 1,
          "type": "array"
        },
        "Signature": {
          "title": "Reminder. Signature",
          "description": "A signature applied to this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Signature"
          },
          "minItems": 1,
          "type": "array"
        },
        "AccountingSupplierParty": {
          "title": "Reminder. Accounting_ Supplier Party. Supplier Party",
          "description": "The accounting supplier party.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AccountingSupplierParty"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "AccountingCustomerParty": {
          "title": "Reminder. Accounting_ Customer Party. Customer Party",
          "description": "The accounting customer party.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AccountingCustomerParty"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "PayeeParty": {
          "title": "Reminder. Payee_ Party. Party",
          "description": "The payee.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/PayeeParty"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "TaxRepresentativeParty": {
          "title": "Reminder. Tax Representative_ Party. Party",
          "description": "The tax representative.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/TaxRepresentativeParty"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "PaymentMeans": {
          "title": "Reminder. Payment Means",
          "description": "Expected means of payment.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/PaymentMeans"
          },
          "minItems": 1,
          "type": "array"
        },
        "PaymentTerms": {
          "title": "Reminder. Payment Terms",
          "description": "A set of payment terms associated with this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/PaymentTerms"
          },
          "minItems": 1,
          "type": "array"
        },
        "PrepaidPayment": {
          "title": "Reminder. Prepaid_ Payment. Payment",
          "description": "A prepaid payment.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/PrepaidPayment"
          },
          "minItems": 1,
          "type": "array"
        },
        "AllowanceCharge": {
          "title": "Reminder. Allowance Charge",
          "description": "A discount or charge that applies to a price component.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AllowanceCharge"
          },
          "minItems": 1,
          "type": "array"
        },
        "TaxExchangeRate": {
          "title": "Reminder. Tax_ Exchange Rate. Exchange Rate",
          "description": "The exchange rate between the document currency and the tax currency.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/TaxExchangeRate"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "PricingExchangeRate": {
          "title": "Reminder. Pricing_ Exchange Rate. Exchange Rate",
          "description": "The exchange rate between the document currency and the pricing currency.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/PricingExchangeRate"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "PaymentExchangeRate": {
          "title": "Reminder. Payment_ Exchange Rate. Exchange Rate",
          "description": "The exchange rate between the document currency and the payment currency.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/PaymentExchangeRate"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "PaymentAlternativeExchangeRate": {
          "title": "Reminder. Payment Alternative_ Exchange Rate. Exchange Rate",
          "description": "The exchange rate between the document currency and the payment alternative currency.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/PaymentAlternativeExchangeRate"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "TaxTotal": {
          "title": "Reminder. Tax Total",
          "description": "The total amount of a specific type of tax.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/TaxTotal"
          },
          "minItems": 1,
          "type": "array"
        },
        "LegalMonetaryTotal": {
          "title": "Reminder. Legal_ Monetary Total. Monetary Total",
          "description": "The total amount payable on the Invoice, including Allowances, Charges, and Taxes.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/LegalMonetaryTotal"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "ReminderLine": {
          "title": "Reminder. Reminder Line",
          "description": "A line describing a payment past due.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ReminderLine"
          },
          "minItems": 1,
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object"
    }
  }
}

=== Pratikshit26/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-legacy/UBL-Reminder-2.1-Example.json
{
  "_D": "urn:oasis:names:specification:ubl:schema:xsd:Reminder-2",
  "_A": "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
  "_B": "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2",
  "Reminder": [
    {
      "UBLVersionID": [{ "_": "2.1" }],
      "ID": [{ "_": "12" }],
      "IssueDate": [{ "_": "2010-04-14" }],
      "AccountingSupplierParty": [
        {
          "Party": [
            {
              "EndpointID": [
                {
                  "_": "1234567890123",
                  "schemeID": "GLN",
                  "schemeAgencyID": "9"
                }
              ],
              "PartyIdentification": [
                {
                  "ID": [{ "_": "Supp123", "schemeID": "ZZZ" }]
                }
              ],
              "PartyName": [
                {
                  "Name": [{ "_": "Salescompany ltd." }]
                }
              ],
              "PostalAddress": [
                {
                  "ID": [
                    {
                      "_": "1231412341324",
                      "schemeID": "GLN",
                      "schemeAgencyID": "9"
                    }
                  ],
                  "Postbox": [{ "_": "5467" }],
                  "StreetName": [{ "_": "Main street" }],
                  "AdditionalStreetName": [{ "_": "Suite 123" }],
                  "BuildingNumber": [{ "_": "1" }],
                  "Department": [{ "_": "Revenue department" }],
                  "CityName": [{ "_": "Big city" }],
                  "PostalZone": [{ "_": "54321" }],
                  "CountrySubentityCode": [{ "_": "RegionA" }],
                  "Country": [
                    {
                      "IdentificationCode": [
                        {
                          "_": "DK",
                          "listID": "ISO3166-1",
                          "listAgencyID": "6"
                        }
                      ]
                    }
                  ]
                }
              ],
              "PartyTaxScheme": [
                {
                  "CompanyID": [
                    {
                      "_": "DK12345",
                      "schemeID": "DKVAT",
                      "schemeAgencyID": "ZZZ"
                    }
                  ],
                  "TaxScheme": [
                    {
                      "ID": [
                        {
                          "_": "VAT",
                          "schemeID": "UN/ECE 5153",
                          "schemeAgencyID": "6"
                        }
                      ]
                    }
                  ]
                }
              ],
              "PartyLegalEntity": [
                {
                  "RegistrationName": [
                    { "_": "The Sellercompany Incorporated" }
                  ],
                  "CompanyID": [
                    {
                      "_": "5402697509",
                      "schemeID": "CVR",
                      "schemeAgencyID": "ZZZ"
                    }
                  ],
                  "RegistrationAddress": [
                    {
                      "CityName": [{ "_": "Big city" }],
                      "CountrySubentity": [{ "_": "RegionA" }],
                      "Country": [
                        {
                          "IdentificationCode": [{ "_": "DK" }]
                        }
                      ]
                    }
                  ]
                }
              ],
              "Contact": [
                {
                  "Telephone": [{ "_": "4621230" }],
                  "Telefax": [{ "_": "4621231" }],
                  "ElectronicMail": [{ "_": "antonio@salescompany.dk" }]
                }
              ],
              "Person": [
                {
                  "FirstName": [{ "_": "Antonio" }],
                  "FamilyName": [{ "_": "M" }],
                  "MiddleName": [{ "_": "Salemacher" }],
                  "JobTitle": [{ "_": "Sales manager" }]
                }
              ]
            }
          ]
        }
      ],
      "AccountingCustomerParty": [
        {
          "Party": [
            {
              "EndpointID": [
                {
                  "_": "1234567987654",
                  "schemeID": "GLN",
                  "schemeAgencyID": "9"
                }
              ],
              "PartyIdentification": [
                {
                  "ID": [{ "_": "345KS5324", "schemeID": "ZZZ" }]
                }
              ],
              "PartyName": [
                {
                  "Name": [{ "_": "Buyercompany ltd" }]
                }
              ],
              "PostalAddress": [
                {
                  "ID": [
                    {
                      "_": "1238764941386",
                      "schemeID": "GLN",
                      "schemeAgencyID": "9"
                    }
                  ],
                  "Postbox": [{ "_": "123" }],
                  "StreetName": [{ "_": "Anystreet" }],
                  "AdditionalStreetName": [{ "_": "Back door" }],
                  "BuildingNumber": [{ "_": "8" }],
                  "Department": [{ "_": "Accounting department" }],
                  "CityName": [{ "_": "Anytown" }],
                  "PostalZone": [{ "_": "101" }],
                  "CountrySubentity": [{ "_": "RegionB" }],
                  "Country": [
                    {
                      "IdentificationCode": [
                        {
                          "_": "BE",
                          "listID": "ISO3166-1",
                          "listAgencyID": "6"
                        }
                      ]
                    }
                  ]
                }
              ],
              "PartyTaxScheme": [
                {
                  "CompanyID": [
                    {
                      "_": "BE54321",
                      "schemeID": "BEVAT",
                      "schemeAgencyID": "ZZZ"
                    }
                  ],
                  "TaxScheme": [
                    {
                      "ID": [
                        {
                          "_": "VAT",
                          "schemeID": "UN/ECE 5153",
                          "schemeAgencyID": "6"
                        }
                      ]
                    }
                  ]
                }
              ],
              "PartyLegalEntity": [
                {
                  "RegistrationName": [{ "_": "The buyercompany inc." }],
                  "CompanyID": [
                    {
                      "_": "5645342123",
                      "schemeAgencyID": "ZZZ",
                      "schemeID": "ZZZ"
                    }
                  ],
                  "RegistrationAddress": [
                    {
                      "CityName": [{ "_": "Mainplace" }],
                      "CountrySubentity": [{ "_": "RegionB" }],
                      "Country": [
                        {
                          "IdentificationCode": [{ "_": "BE" }]
                        }
                      ]
                    }
                  ]
                }
              ],
              "Contact": [
                {
                  "Telephone": [{ "_": "5121230" }],
                  "Telefax": [{ "_": "5121231" }],
                  "ElectronicMail": [{ "_": "john@buyercompany.eu" }]
                }
              ],
              "Person": [
                {
                  "FirstName": [{ "_": "John" }],
                  "FamilyName": [{ "_": "X" }],
                  "MiddleName": [{ "_": "Doe" }],
                  "JobTitle": [{ "_": "Purchasing manager" }]
                }
              ]
            }
          ]
        }
      ],
      "LegalMonetaryTotal": [
        {
          "LineExtensionAmount": [{ "_": 1436.5, "currencyID": "EUR" }],
          "TaxExclusiveAmount": [{ "_": 1436.5, "currencyID": "EUR" }],
          "TaxInclusiveAmount": [{ "_": 1729, "currencyID": "EUR" }],
          "AllowanceTotalAmount": [{ "_": 100, "currencyID": "EUR" }],
          "ChargeTotalAmount": [{ "_": 100, "currencyID": "EUR" }],
          "PrepaidAmount": [{ "_": 1000, "currencyID": "EUR" }],
          "PayableRoundingAmount": [{ "_": 0.3, "currencyID": "EUR" }],
          "PayableAmount": [{ "_": 729, "currencyID": "EUR" }]
        }
      ],
      "ReminderLine": [
        {
          "ID": [{ "_": "1" }],
          "BillingReference": [
            {
              "InvoiceDocumentReference": [
                {
                  "ID": [{ "_": "TOSL108" }]
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
