=== Pratikshit26/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-schema-legacy/maindoc/UBL-BusinessCard-2.3.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "json-schema-legacy/maindoc/UBL-BusinessCard-2.3.json",
  "description": "\n  Library:           OASIS Universal Business Language (UBL) 2.3 OS\n                     http://docs.oasis-open.org/ubl/os-UBL-2.3/\n  Release Date:      15 June 2021\n  Module:            json-schema-legacy/maindoc/UBL-BusinessCard-2.3.json\n  Generated on:      2021-12-15 21:56z\n  Copyright (c) OASIS Open 2021. All Rights Reserved.\n\n\n  OASIS takes no position regarding the validity or scope of any \n  intellectual property or other rights that might be claimed to pertain \n  to the implementation or use of the technology described in this \n  document or the extent to which any license under such rights \n  might or might not be available; neither does it represent that it has \n  made any effort to identify any such rights. Information on OASIS's \n  procedures with respect to rights in OASIS specifications can be \n  found at the OASIS website. Copies of claims of rights made \n  available for publication and any assurances of licenses to be made \n  available, or the result of an attempt made to obtain a general \n  license or permission for the use of such proprietary rights by \n  implementors or users of this specification, can be obtained from \n  the OASIS Executive Director.\n\n  OASIS invites any interested party to bring to its attention any \n  copyrights, patents or patent applications, or other proprietary \n  rights which may cover technology that may be required to \n  implement this specification. Please address the information to the \n  OASIS Executive Director.\n  \n  This document and translations of it may be copied and furnished to \n  others, and derivative works that comment on or otherwise explain \n  it or assist in its implementation may be prepared, copied, \n  published and distributed, in whole or in part, without restriction of \n  any kind, provided that the above copyright notice and this \n  paragraph are included on all such copies and derivative works. \n  However, this document itself may not be modified in any way, \n  such as by removing the copyright notice or references to OASIS, \n  except as needed for the purpose of developing OASIS \n  specifications, in which case the procedures for copyrights defined \n  in the OASIS Intellectual Property Rights document must be \n  followed, or as required to translate it into languages other than \n  English. \n\n  The limited permissions granted above are perpetual and will not be \n  revoked by OASIS or its successors or assigns. \n\n  This document and the information contained herein is provided on \n  an \"AS IS\" basis and OASIS DISCLAIMS ALL WARRANTIES, \n  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY \n  WARRANTY THAT THE USE OF THE INFORMATION HEREIN \n  WILL NOT INFRINGE ANY RIGHTS OR ANY IMPLIED \n  WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A \n  PARTICULAR PURPOSE.    \n",
  "required": ["BusinessCard"],
  "properties": {
    "_D": {
      "description": "Document ABIE XML namespace string",
      "type": "string"
    },
    "_A": {
      "description": "Library ABIE XML namespace string (for ASBIEs)",
      "type": "string"
    },
    "_B": {
      "description": "BBIE XML namespace string",
      "type": "string"
    },
    "_E": {
      "description": "Extension scaffolding XML namespace string",
      "type": "string"
    },
    "BusinessCard": {
      "description": "A document used to provide information about a business party and its business capabilities.",
      "items": {
        "$ref": "#/definitions/BusinessCard"
      },
      "maxItems": 1,
      "minItems": 1,
      "type": "array"
    }
  },
  "additionalProperties": false,
  "type": "object",
  "definitions": {
    "BusinessCard": {
      "title": "Business Card. Details",
      "description": "A document used to provide information about a business party and its business capabilities.",
      "required": ["ID", "IssueDate", "BusinessParty"],
      "properties": {
        "UBLExtensions": {
          "title": "UBLExtensions",
          "description": "An optional set of extensions to the committee model",
          "items": {
            "$ref": "../common/UBL-CommonExtensionComponents-2.3.json#/definitions/UBLExtensions"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },

        "UBLVersionID": {
          "title": "Business Card. UBL Version Identifier. Identifier",
          "description": "Identifies the earliest version of the UBL 2 schema for this document type that defines all of the elements that might be encountered in the current instance.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UBLVersionID"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "CustomizationID": {
          "title": "Business Card. Customization Identifier. Identifier",
          "description": "Identifies a user-defined customization of UBL for a specific use.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CustomizationID"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "ProfileID": {
          "title": "Business Card. Profile Identifier. Identifier",
          "description": "Identifies a user-defined profile of the customization of UBL being used.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileID"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "ProfileExecutionID": {
          "title": "Business Card. Profile Execution Identifier. Identifier",
          "description": "Identifies an instance of executing a profile, to associate all transactions in a collaboration.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileExecutionID"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "ID": {
          "title": "Business Card. Identifier",
          "description": "An identifier for this document, assigned by the sender.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ID"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "UUID": {
          "title": "Business Card. UUID. Identifier",
          "description": "A universally unique identifier for an instance of this document.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UUID"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "IssueDate": {
          "title": "Business Card. Issue Date. Date",
          "description": "The date, assigned by the sender, on which this document was issued.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueDate"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "IssueTime": {
          "title": "Business Card. Issue Time. Time",
          "description": "The time, assigned by the sender, at which this document was issued.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueTime"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "VersionID": {
          "title": "Business Card. Version Identifier. Identifier",
          "description": "Identifies the current version of this business card.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/VersionID"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "PreviousVersionID": {
          "title": "Business Card. Previous Version Identifier. Identifier",
          "description": "Identifies the previous version of this business card.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/PreviousVersionID"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "BriefDescription": {
          "title": "Business Card. Brief_ Description. Text",
          "description": "Textual description of the document instance.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/BriefDescription"
          },
          "minItems": 1,
          "type": "array"
        },
        "Signature": {
          "title": "Business Card. Signature",
          "description": "A signature applied to this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Signature"
          },
          "minItems": 1,
          "type": "array"
        },
        "SenderParty": {
          "title": "Business Card. Sender_ Party. Party",
          "description": "The party sending this business card. This party could be the owner of this business card or a third-party acting on behalf of the owner (e.g. business network).",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/SenderParty"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "ReceiverParty": {
          "title": "Business Card. Receiver_ Party. Party",
          "description": "The party receiving this business card.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ReceiverParty"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "BusinessParty": {
          "title": "Business Card. Business_ Party. Party",
          "description": "The party owning this business card.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/BusinessParty"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "BrochureDocumentReference": {
          "title": "Business Card. Brochure_ Document Reference. Document Reference",
          "description": "A reference to a company brochure document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/BrochureDocumentReference"
          },
          "minItems": 1,
          "type": "array"
        },
        "AdditionalDocumentReference": {
          "title": "Business Card. Additional_ Document Reference. Document Reference",
          "description": "A reference to an additional document (e.g. presentations).",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AdditionalDocumentReference"
          },
          "minItems": 1,
          "type": "array"
        },
        "BusinessCapability": {
          "title": "Business Card. Business_ Capability. Capability",
          "description": "The business capabilities of the party.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/BusinessCapability"
          },
          "minItems": 1,
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object"
    }
  }
}

=== Pratikshit26/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-legacy/UBL-BusinessCard-2.2-Example.json
{
  "_D": "urn:oasis:names:specification:ubl:schema:xsd:BusinessCard-2",
  "_A": "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
  "_B": "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2",
  "BusinessCard": [
    {
      "UBLVersionID": [{ "_": "2.2" }],
      "ID": [{ "_": "BC1-2016" }],
      "IssueDate": [{ "_": "2016-11-07" }],
      "VersionID": [{ "_": "1.1" }],
      "PreviousVersionID": [{ "_": "1.0" }],
      "BriefDescription": [
        {
          "_": "OASIS is a nonprofit consortium that drives the development, convergence and adoption of open standards for the global information society.  OASIS promotes industry consensus and produces worldwide standards for security, Internet of Things, cloud computing, energy, content technologies, emergency management, and other areas. OASIS open standards offer the potential to lower cost, stimulate innovation, grow global markets, and protect the right of free choice of technology.  OASIS members broadly represent the marketplace of public and private sector technology leaders, users and influencers. The consortium has more than 5,000 participants representing over 600 organizations and individual members in more than 65 countries.  OASIS is distinguished by its transparent governance and operating procedures. Members themselves set the OASIS technical agenda, using a lightweight process expressly designed to promote industry consensus and unite disparate efforts. Completed work is ratified by open ballot. Governance is accountable and unrestricted. Officers of both the OASIS Board of Directors and Technical Advisory Board are chosen by democratic election to serve two-year terms. Consortium leadership is based on individual merit and is not tied to financial contribution, corporate standing, or special appointment.  OASIS Member Sections include AMQP, Emergency, IDtrust, LegalXML, Open CSA, OSLC, and WS-I."
        }
      ],
      "SenderParty": [
        {
          "WebsiteURI": [{ "_": "https://www.oasis-open.org" }],
          "LogoReferenceID": [
            {
              "_": "https://www.oasis-open.org/sites/www.oasis-open.org/files/logo.png"
            }
          ],
          "PartyName": [
            {
              "Name": [{ "_": "OASIS" }]
            },
            {
              "Name": [
                {
                  "_": "Organization for the Advancement of Structured Information Standards"
                }
              ]
            }
          ],
          "PostalAddress": [
            {
              "StreetName": [{ "_": "Corporate Drive Suite 150" }],
              "BuildingNumber": [{ "_": "35" }],
              "CityName": [{ "_": "Burlington" }],
              "PostalZone": [{ "_": "01803-4238" }],
              "CountrySubentityCode": [{ "_": "MA" }],
              "Country": [
                {
                  "IdentificationCode": [{ "_": "US" }]
                }
              ]
            }
          ],
          "PhysicalLocation": [
            {
              "InformationURI": [{ "_": "https://goo.gl/maps/2k242" }]
            }
          ],
          "Contact": [
            {
              "ID": [{ "_": "1" }],
              "Telephone": [{ "_": "+1 781 425 5073" }],
              "Telefax": [{ "_": "+1 781 425 5072" }],
              "ElectronicMail": [{ "_": "info@oasis-open.org" }]
            }
          ],
          "AdditionalWebSite": [
            {
              "ID": [{ "_": "1" }],
              "Name": [{ "_": "RSS" }],
              "URI": [{ "_": "https://www.oasis-open.org/feed" }]
            }
          ],
          "SocialMediaProfile": [
            {
              "ID": [{ "_": "1" }],
              "Name": [{ "_": "LinkedIN" }],
              "SocialMediaTypeCode": [{ "_": "Business" }],
              "URI": [{ "_": "https://www.linkedin.com/company/oasis" }]
            },
            {
              "ID": [{ "_": "2" }],
              "Name": [{ "_": "Twitter" }],
              "URI": [{ "_": "http://twitter.com/OASISopen" }]
            },
            {
              "ID": [{ "_": "3" }],
              "Name": [{ "_": "Facebook" }],
              "URI": [{ "_": "http://facebook.com/oasis.open" }]
            },
            {
              "ID": [{ "_": "4" }],
              "Name": [{ "_": "YouTube" }],
              "URI": [{ "_": "http://www.youtube.com/oasisopen" }]
            },
            {
              "ID": [{ "_": "5" }],
              "Name": [{ "_": "Google+" }],
              "URI": [{ "_": "https://plus.google.com/+Oasis-openOrg" }]
            }
          ]
        }
      ],
      "BusinessParty": [
        {
          "EndpointID": [
            { "_": "9994567987654", "schemeID": "GLN", "schemeAgencyID": "9" }
          ],
          "PartyIdentification": [
            {
              "ID": [{ "_": "GB999999973", "schemeID": "GB:VAT" }]
            }
          ],
          "PartyName": [
            {
              "Name": [{ "_": "World Events Ltd." }]
            }
          ],
          "PostalAddress": [
            {
              "CityName": [{ "_": "London" }],
              "Country": [
                {
                  "IdentificationCode": [{ "_": "GB" }]
                }
              ]
            }
          ]
        }
      ],
      "BusinessCapability": [
        {
          "CapabilityTypeCode": [{ "_": "General" }],
          "Description": [
            { "_": "Advancing open standards for the information society." }
          ]
        }
      ]
    }
  ]
}
