=== Pratikshit26/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-schema-legacy/maindoc/UBL-ProofOfReexportationRequest-2.3.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "json-schema-legacy/maindoc/UBL-ProofOfReexportationRequest-2.3.json",
  "description": "\n  Library:           OASIS Universal Business Language (UBL) 2.3 OS\n                     http://docs.oasis-open.org/ubl/os-UBL-2.3/\n  Release Date:      15 June 2021\n  Module:            json-schema-legacy/maindoc/UBL-ProofOfReexportationRequest-2.3.json\n  Generated on:      2021-12-15 21:56z\n  Copyright (c) OASIS Open 2021. All Rights Reserved.\n\n\n  OASIS takes no position regarding the validity or scope of any \n  intellectual property or other rights that might be claimed to pertain \n  to the implementation or use of the technology described in this \n  document or the extent to which any license under such rights \n  might or might not be available; neither does it represent that it has \n  made any effort to identify any such rights. Information on OASIS's \n  procedures with respect to rights in OASIS specifications can be \n  found at the OASIS website. Copies of claims of rights made \n  available for publication and any assurances of licenses to be made \n  available, or the result of an attempt made to obtain a general \n  license or permission for the use of such proprietary rights by \n  implementors or users of this specification, can be obtained from \n  the OASIS Executive Director.\n\n  OASIS invites any interested party to bring to its attention any \n  copyrights, patents or patent applications, or other proprietary \n  rights which may cover technology that may be required to \n  implement this specification. Please address the information to the \n  OASIS Executive Director.\n  \n  This document and translations of it may be copied and furnished to \n  others, and derivative works that comment on or otherwise explain \n  it or assist in its implementation may be prepared, copied, \n  published and distributed, in whole or in part, without restriction of \n  any kind, provided that the above copyright notice and this \n  paragraph are included on all such copies and derivative works. \n  However, this document itself may not be modified in any way, \n  such as by removing the copyright notice or references to OASIS, \n  except as needed for the purpose of developing OASIS \n  specifications, in which case the procedures for copyrights defined \n  in the OASIS Intellectual Property Rights document must be \n  followed, or as required to translate it into languages other than \n  English. \n\n  The limited permissions granted above are perpetual and will not be \n  revoked by OASIS or its successors or assigns. \n\n  This document and the information contained herein is provided on \n  an \"AS IS\" basis and OASIS DISCLAIMS ALL WARRANTIES, \n  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY \n  WARRANTY THAT THE USE OF THE INFORMATION HEREIN \n  WILL NOT INFRINGE ANY RIGHTS OR ANY IMPLIED \n  WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A \n  PARTICULAR PURPOSE.    \n",
  "required": ["ProofOfReexportationRequest"],
  "properties": {
    "_D": {
      "description": "Document ABIE XML namespace string",
      "type": "string"
    },
    "_A": {
      "description": "Library ABIE XML namespace string (for ASBIEs)",
      "type": "string"
    },
    "_B": {
      "description": "BBIE XML namespace string",
      "type": "string"
    },
    "_E": {
      "description": "Extension scaffolding XML namespace string",
      "type": "string"
    },
    "ProofOfReexportationRequest": {
      "description": "A document requesting the status or proof that goods have been re-exported",
      "items": {
        "$ref": "#/definitions/ProofOfReexportationRequest"
      },
      "maxItems": 1,
      "minItems": 1,
      "type": "array"
    }
  },
  "additionalProperties": false,
  "type": "object",
  "definitions": {
    "ProofOfReexportationRequest": {
      "title": "Proof Of Reexportation Request. Details",
      "description": "A document requesting the status or proof that goods have been re-exported",
      "required": [
        "ID",
        "GoodsItemPassportID",
        "ImportingGuarantorParty",
        "ExportingGuarantorParty"
      ],
      "properties": {
        "UBLExtensions": {
          "title": "UBLExtensions",
          "description": "An optional set of extensions to the committee model",
          "items": {
            "$ref": "../common/UBL-CommonExtensionComponents-2.3.json#/definitions/UBLExtensions"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },

        "UBLVersionID": {
          "title": "Proof Of Reexportation Request. UBL Version Identifier. Identifier",
          "description": "Identifies the earliest version of the UBL 2 schema for this document type that defines all of the elements that might be encountered in the current instance.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UBLVersionID"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "CustomizationID": {
          "title": "Proof Of Reexportation Request. Customization Identifier. Identifier",
          "description": "Identifies a user-defined customization of UBL for a specific use.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CustomizationID"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "ProfileID": {
          "title": "Proof Of Reexportation Request. Profile Identifier. Identifier",
          "description": "Identifies a user-defined profile of the customization of UBL being used.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileID"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "ProfileExecutionID": {
          "title": "Proof Of Reexportation Request. Profile Execution Identifier. Identifier",
          "description": "Identifies an instance of executing a profile, to associate all transactions in a collaboration.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileExecutionID"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "ID": {
          "title": "Proof Of Reexportation Request. Identifier",
          "description": "An identifier for this document, assigned by the sender.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ID"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "UUID": {
          "title": "Proof Of Reexportation Request. UUID. Identifier",
          "description": "A universally unique identifier for an instance of this document.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UUID"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "IssueDate": {
          "title": "Proof Of Reexportation Request. Issue Date. Date",
          "description": "The date, assigned by the sender, on which this document was issued.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueDate"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "IssueTime": {
          "title": "Proof Of Reexportation Request. Issue Time. Time",
          "description": "The time, assigned by the sender, at which this document was issued.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueTime"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "Note": {
          "title": "Proof Of Reexportation Request. Note. Text",
          "description": "Free-form text pertinent to this document, conveying information that is not contained explicitly in other structures.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/Note"
          },
          "minItems": 1,
          "type": "array"
        },
        "VersionID": {
          "title": "Proof Of Reexportation Request. Version. Identifier",
          "description": "Identifies the current version of this request for proof",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/VersionID"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "GoodsItemPassportID": {
          "title": "Proof Of Reexportation Request. Goods Item Passport. Identifier",
          "description": "The identifier of the goods item passport or ATA Carnet of the goods",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/GoodsItemPassportID"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "GoodsItemPassportCounterfoilID": {
          "title": "Proof Of Reexportation Request. Goods Item Passport Counterfoil. Identifier",
          "description": "A reference to a counterfoil of the goods item passport or ATA Carnet",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/GoodsItemPassportCounterfoilID"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "ImportingGuarantorParty": {
          "title": "Proof Of Reexportation Request. Importing Guarantor_ Party. Party",
          "description": "The party (often chambers of commerce) who issues this document on behalf of their customs authority.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ImportingGuarantorParty"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "ExportingGuarantorParty": {
          "title": "Proof Of Reexportation Request. Exporting Guarantor_ Party. Party",
          "description": "The party (often chambers of commerce) who are fiscally responsible for the Goods Item Passort counterfoils associated with this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ExportingGuarantorParty"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "ImportingCustomsParty": {
          "title": "Proof Of Reexportation Request. Importing Customs_ Party. Party",
          "description": "The original requester of the proof of reexportation.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ImportingCustomsParty"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "AdditionalDocumentReference": {
          "title": "Proof Of Reexportation Request. Additional_ Document Reference. Document Reference",
          "description": "One or more references to additional documents related to this request",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AdditionalDocumentReference"
          },
          "minItems": 1,
          "type": "array"
        },
        "Signature": {
          "title": "Proof Of Reexportation Request. Signature",
          "description": "A signature applied to this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Signature"
          },
          "minItems": 1,
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object"
    }
  }
}

=== Pratikshit26/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-legacy/UBL-ProofOfReexportationRequest-2.3-Example.json
{
  "_D": "urn:oasis:names:specification:ubl:schema:xsd:ProofOfReexportationRequest-2",
  "_A": "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
  "_B": "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2",
  "ProofOfReexportationRequest": [
    {
      "ID": [{ "_": "A2344" }],
      "IssueDate": [{ "_": "2019-06-21" }],
      "GoodsItemPassportID": [{ "_": "234222" }],
      "ImportingGuarantorParty": [
        {
          "PartyName": [
            {
              "Name": [
                { "_": "Deutscher Industrie- und Handelskammertag e.V." }
              ]
            }
          ],
          "PostalAddress": [
            {
              "StreetName": [{ "_": "Breite Straße" }],
              "BuildingNumber": [{ "_": "29" }],
              "CityName": [{ "_": "Berlin" }],
              "PostalZone": [{ "_": "10178" }],
              "Country": [
                {
                  "IdentificationCode": [{ "_": "DE" }]
                }
              ]
            }
          ],
          "PartyLegalEntity": [
            {
              "CompanyID": [{ "_": "DE122125278" }]
            }
          ]
        }
      ],
      "ExportingGuarantorParty": [
        {
          "PartyName": [
            {
              "Name": [{ "_": "Dansk Erhverv" }]
            }
          ],
          "PostalAddress": [
            {
              "StreetName": [{ "_": "Slotsholmsgade" }],
              "BuildingNumber": [{ "_": "1" }],
              "CityName": [{ "_": "København K" }],
              "PostalZone": [{ "_": "1216" }],
              "Country": [
                {
                  "IdentificationCode": [{ "_": "DK" }]
                }
              ]
            }
          ],
          "PartyLegalEntity": [
            {
              "CompanyID": [{ "_": "DK43232010" }]
            }
          ]
        }
      ],
      "ImportingCustomsParty": [
        {
          "PartyName": [
            {
              "Name": [{ "_": "Zollamt" }]
            }
          ],
          "PostalAddress": [
            {
              "StreetName": [{ "_": "Tollbrettkoppel" }],
              "BuildingNumber": [{ "_": "8" }],
              "CityName": [{ "_": "Heiligenhafen" }],
              "PostalZone": [{ "_": "23774" }],
              "Country": [
                {
                  "IdentificationCode": [{ "_": "DE" }]
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
