=== Pratikshit26/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-schema-legacy/maindoc/UBL-OrderCancellation-2.3.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "json-schema-legacy/maindoc/UBL-OrderCancellation-2.3.json",
  "description": "\n  Library:           OASIS Universal Business Language (UBL) 2.3 OS\n                     http://docs.oasis-open.org/ubl/os-UBL-2.3/\n  Release Date:      15 June 2021\n  Module:            json-schema-legacy/maindoc/UBL-OrderCancellation-2.3.json\n  Generated on:      2021-12-15 21:56z\n  Copyright (c) OASIS Open 2021. All Rights Reserved.\n\n\n  OASIS takes no position regarding the validity or scope of any \n  intellectual property or other rights that might be claimed to pertain \n  to the implementation or use of the technology described in this \n  document or the extent to which any license under such rights \n  might or might not be available; neither does it represent that it has \n  made any effort to identify any such rights. Information on OASIS's \n  procedures with respect to rights in OASIS specifications can be \n  found at the OASIS website. Copies of claims of rights made \n  available for publication and any assurances of licenses to be made \n  available, or the result of an attempt made to obtain a general \n  license or permission for the use of such proprietary rights by \n  implementors or users of this specification, can be obtained from \n  the OASIS Executive Director.\n\n  OASIS invites any interested party to bring to its attention any \n  copyrights, patents or patent applications, or other proprietary \n  rights which may cover technology that may be required to \n  implement this specification. Please address the information to the \n  OASIS Executive Director.\n  \n  This document and translations of it may be copied and furnished to \n  others, and derivative works that comment on or otherwise explain \n  it or assist in its implementation may be prepared, copied, \n  published and distributed, in whole or in part, without restriction of \n  any kind, provided that the above copyright notice and this \n  paragraph are included on all such copies and derivative works. \n  However, this document itself may not be modified in any way, \n  such as by removing the copyright notice or references to OASIS, \n  except as needed for the purpose of developing OASIS \n  specifications, in which case the procedures for copyrights defined \n  in the OASIS Intellectual Property Rights document must be \n  followed, or as required to translate it into languages other than \n  English. \n\n  The limited permissions granted above are perpetual and will not be \n  revoked by OASIS or its successors or assigns. \n\n  This document and the information contained herein is provided on \n  an \"AS IS\" basis and OASIS DISCLAIMS ALL WARRANTIES, \n  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY \n  WARRANTY THAT THE USE OF THE INFORMATION HEREIN \n  WILL NOT INFRINGE ANY RIGHTS OR ANY IMPLIED \n  WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A \n  PARTICULAR PURPOSE.    \n",
  "required": ["OrderCancellation"],
  "properties": {
    "_D": {
      "description": "Document ABIE XML namespace string",
      "type": "string"
    },
    "_A": {
      "description": "Library ABIE XML namespace string (for ASBIEs)",
      "type": "string"
    },
    "_B": {
      "description": "BBIE XML namespace string",
      "type": "string"
    },
    "_E": {
      "description": "Extension scaffolding XML namespace string",
      "type": "string"
    },
    "OrderCancellation": {
      "description": "A document used to cancel an entire Order.",
      "items": {
        "$ref": "#/definitions/OrderCancellation"
      },
      "maxItems": 1,
      "minItems": 1,
      "type": "array"
    }
  },
  "additionalProperties": false,
  "type": "object",
  "definitions": {
    "OrderCancellation": {
      "title": "Order Cancellation. Details",
      "description": "A document used to cancel an entire Order.",
      "required": [
        "ID",
        "IssueDate",
        "CancellationNote",
        "OrderReference",
        "BuyerCustomerParty",
        "SellerSupplierParty"
      ],
      "properties": {
        "UBLExtensions": {
          "title": "UBLExtensions",
          "description": "An optional set of extensions to the committee model",
          "items": {
            "$ref": "../common/UBL-CommonExtensionComponents-2.3.json#/definitions/UBLExtensions"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },

        "UBLVersionID": {
          "title": "Order Cancellation. UBL Version Identifier. Identifier",
          "description": "Identifies the earliest version of the UBL 2 schema for this document type that defines all of the elements that might be encountered in the current instance.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UBLVersionID"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "CustomizationID": {
          "title": "Order Cancellation. Customization Identifier. Identifier",
          "description": "Identifies a user-defined customization of UBL for a specific use.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CustomizationID"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "ProfileID": {
          "title": "Order Cancellation. Profile Identifier. Identifier",
          "description": "Identifies a user-defined profile of the customization of UBL being used.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileID"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "ProfileExecutionID": {
          "title": "Order Cancellation. Profile Execution Identifier. Identifier",
          "description": "Identifies an instance of executing a profile, to associate all transactions in a collaboration.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileExecutionID"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "ID": {
          "title": "Order Cancellation. Identifier",
          "description": "An identifier for this document, assigned by the sender.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ID"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "CopyIndicator": {
          "title": "Order Cancellation. Copy_ Indicator. Indicator",
          "description": "Indicates whether this document is a copy (true) or not (false).",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CopyIndicator"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "UUID": {
          "title": "Order Cancellation. UUID. Identifier",
          "description": "A universally unique identifier for an instance of this document.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UUID"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "IssueDate": {
          "title": "Order Cancellation. Issue Date. Date",
          "description": "The date, assigned by the sender, on which this document was issued.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueDate"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "IssueTime": {
          "title": "Order Cancellation. Issue Time. Time",
          "description": "The time, assigned by the sender, at which this document was issued.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueTime"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "Note": {
          "title": "Order Cancellation. Note. Text",
          "description": "Free-form text pertinent to this document, conveying information that is not contained explicitly in other structures.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/Note"
          },
          "minItems": 1,
          "type": "array"
        },
        "CancellationNote": {
          "title": "Order Cancellation. Cancellation_ Note. Text",
          "description": "The general reason for cancellation of the referenced order.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CancellationNote"
          },
          "minItems": 1,
          "type": "array"
        },
        "OrderReference": {
          "title": "Order Cancellation. Order Reference",
          "description": "A reference to the Order being cancelled. While multiple references are allowed, it is considered better practice to cancel only one Order in each Order Cancellation document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/OrderReference"
          },
          "minItems": 1,
          "type": "array"
        },
        "OriginatorDocumentReference": {
          "title": "Order Cancellation. Originator_ Document Reference. Document Reference",
          "description": "A reference to an originator document associated with this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/OriginatorDocumentReference"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "AdditionalDocumentReference": {
          "title": "Order Cancellation. Additional_ Document Reference. Document Reference",
          "description": "A reference to an additional document associated with this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AdditionalDocumentReference"
          },
          "minItems": 1,
          "type": "array"
        },
        "Contract": {
          "title": "Order Cancellation. Contract",
          "description": "A contract associated with the original Order(s).",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Contract"
          },
          "minItems": 1,
          "type": "array"
        },
        "Signature": {
          "title": "Order Cancellation. Signature",
          "description": "A signature applied to this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Signature"
          },
          "minItems": 1,
          "type": "array"
        },
        "BuyerCustomerParty": {
          "title": "Order Cancellation. Buyer_ Customer Party. Customer Party",
          "description": "The buyer.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/BuyerCustomerParty"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "SellerSupplierParty": {
          "title": "Order Cancellation. Seller_ Supplier Party. Supplier Party",
          "description": "The seller.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/SellerSupplierParty"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "OriginatorCustomerParty": {
          "title": "Order Cancellation. Originator_ Customer Party. Customer Party",
          "description": "The originator.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/OriginatorCustomerParty"
          },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object"
    }
  }
}

=== Pratikshit26/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-legacy/UBL-OrderCancellation-2.1-Example.json
{
  "_D": "urn:oasis:names:specification:ubl:schema:xsd:OrderCancellation-2",
  "_A": "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
  "_B": "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2",
  "OrderCancellation": [
    {
      "UBLVersionID": [{ "_": "2.1" }],
      "CustomizationID": [
        { "_": "urn:www.cenbii.eu:transaction:biicoretrdmXYZ:ver1.0" }
      ],
      "ProfileID": [
        {
          "_": "urn:www.cenbii.eu:profile:BIIXYZ:ver1.0",
          "schemeAgencyID": "BII",
          "schemeID": "Profile"
        }
      ],
      "ID": [{ "_": "7" }],
      "IssueDate": [{ "_": "2010-01-21" }],
      "IssueTime": [{ "_": "12:30:00Z" }],
      "CancellationNote": [{ "_": "With reference to phone call" }],
      "OrderReference": [
        {
          "ID": [{ "_": "34" }]
        }
      ],
      "BuyerCustomerParty": [
        {
          "Party": [
            {
              "EndpointID": [
                {
                  "_": "7300072311115",
                  "schemeAgencyID": "9",
                  "schemeID": "GLN"
                }
              ],
              "PartyIdentification": [
                {
                  "ID": [
                    {
                      "_": "7300070011115",
                      "schemeAgencyID": "9",
                      "schemeID": "GLN"
                    }
                  ]
                },
                {
                  "ID": [{ "_": "PartyID123" }]
                }
              ],
              "PartyName": [
                {
                  "Name": [{ "_": "Johnssons byggvaror" }]
                }
              ]
            }
          ]
        }
      ],
      "SellerSupplierParty": [
        {
          "Party": [
            {
              "EndpointID": [
                {
                  "_": "7302347231111",
                  "schemeAgencyID": "9",
                  "schemeID": "GLN"
                }
              ],
              "PartyIdentification": [
                {
                  "ID": [{ "_": "SellerPartyID123" }]
                }
              ],
              "PartyName": [
                {
                  "Name": [{ "_": "Moderna Produkter AB" }]
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
